In [1]:
try:
  from google.colab import drive
  drive.mount('/content/drive')
  path = "/content/drive/MyDrive/COMP720Project/"
except Exception:
  path = "../data/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pip
pip.main([
    'install',
    'pandas',
    'sentence-transformers',
    'matplotlib',
    'seaborn',
    'scipy',
    'scikit-learn',
    'nltk',
    'tqdm',
    'spacy',
    ])

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)

Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)

Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (1.26.4)

Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)

Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)

Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)

Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)

Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)

Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)

Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)

Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)

Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)

Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)

Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)

Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)

Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)

Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)

Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)

Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)

Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)

Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)

Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)

Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)

Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)

Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)

Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)

Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)

Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)

Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)

Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)

Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)

Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.26.8)

Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)

Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)

Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)

Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)

Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)

Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)

Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)

Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)

Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)

Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)

Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)

Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)

Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)

Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)

Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)

Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)

Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)

Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)

Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)

Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)

Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)

Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)

Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)

Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)

Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)

Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.0)

Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)

Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)

Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)

Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)

Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)

Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)

Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)

Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)

Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

0

In [3]:
import os
import numpy as np
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

NumExpr defaulting to 8 threads.

In [4]:
!pip install replay-rec[torch] -q
!pip install pyspark==3.3.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.9/827.9 kB 21.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 117.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 370.7/370.7 kB 28.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 60.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 54.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Collecting pyspark==3.3.2
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5 (from pyspark==3.3.2)
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 16.4 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824009 sha256=eedb0f8498186d2b87d191bc19877777664e23ab51c858f0460db0b8168dc0f1
  Stored in directory: /root/.cache/pip/wheels/93/99/74/4ba9a39bf51affed2cbf91a45688ea2a125775239338534f85
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.9
    Uninstalling py4j-0.10.9.9:
      Successfully uninstalled py4j-0.10.9.9
  Attempting uninstall: pyspark
    Found existing installation: pyspark 4.0.3
    Uninstalling pyspark-4.0.3:
      Successfully uninstalled pyspark-4.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 1.1.0 requires pyspark[connect]~=4.0.0, but you have pyspark 3.3.2 which is incompatible.
Successfully installed py4j-0.10.9.5 pyspark-3.3.2

In [4]:
from replay.preprocessing import LabelEncoder

ENCODED_DIR = Path(path) / "encoded"
ENCODER_PATH = ENCODED_DIR / "encoder"
INTERACTIONS_PATH = ENCODED_DIR / "encoded_interactions.parquet"
ITEM_FEATURES_PATH = ENCODED_DIR / "item_features_encoded.parquet"

# consumed later by ContentAwareEmbedder / FeaturesReader -- same file, kept under its
# original name so the rest of the notebook doesn't need to change
PATH_ENCODED_FEATURES = ITEM_FEATURES_PATH

encoder = LabelEncoder.load(ENCODER_PATH)
encoded_interactions = pd.read_parquet(INTERACTIONS_PATH)
item_features_encoded = pd.read_parquet(ITEM_FEATURES_PATH)
item_features_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15711 entries, 0 to 15710
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   item_id            15711 non-null  int64
 1   title              15711 non-null  object
 2   genres             15711 non-null  object
 3   genre_names        15711 non-null  object
 4   item_numerics      15711 non-null  object
 5   embeddings         15711 non-null  object
 6   keyword_embedding  15711 non-null  object
dtypes: int64(1), object(6)
memory usage: 859.3+ KB

### Train/val/test split

In [18]:
from replay.splitters import LastNSplitter

splitter = LastNSplitter(
    N=1,
    divide_column="user_id",
    query_column="user_id",
    strategy="interactions",
    drop_cold_users=True,
    drop_cold_items=True
)

test_events, test_gt = splitter.split(encoded_interactions)
validation_events, validation_gt = splitter.split(test_events)
train_events = validation_events

In [21]:
from replay.data.nn.utils import groupby_sequences


def bake_data(full_data):
    return groupby_sequences(events=full_data, groupby_col="user_id", sort_col="timestamp")

In [ ]:
train_events = bake_data(train_events)

validation_events = bake_data(validation_events)
validation_gt = bake_data(validation_gt)

test_events = bake_data(test_events)
test_gt = bake_data(test_gt)

train_events

In [9]:
def add_gt_to_events(events_df, gt_df):
    gt_to_join = gt_df[["user_id", "item_id"]].rename(columns={"item_id": "ground_truth"})

    events_df = events_df.merge(gt_to_join, on="user_id", how="inner")
    return events_df

validation_events = add_gt_to_events(validation_events, validation_gt)
test_events = add_gt_to_events(test_events, test_gt)

In [10]:
for df in (train_events, validation_events, test_events):  # and test_df / predict_df if applicable
    df["rating"] = df["rating"].apply(lambda seq: np.asarray(seq, dtype=np.float32))

In [11]:
data_dir = Path("temp/data/")
data_dir.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = data_dir / "train.parquet"
VAL_PATH = data_dir / "val.parquet"
PREDICT_PATH = data_dir / "test.parquet"

In [12]:
train_events.to_parquet(TRAIN_PATH)
validation_events.to_parquet(VAL_PATH)
test_events.to_parquet(PREDICT_PATH)

### Traing

In [9]:
from replay.data import FeatureHint, FeatureType
from replay.data.nn import TensorFeatureInfo, TensorSchema, TensorFeatureSource
from replay.data import FeatureSource

EMBEDDING_DIM = 64

NUM_UNIQUE_ITEMS = len(encoder.mapping["item_id"])

tensor_schema = TensorSchema(
    [
        TensorFeatureInfo(
            name="item_id",
            is_seq=True,
            padding_value=NUM_UNIQUE_ITEMS,
            cardinality=NUM_UNIQUE_ITEMS,
            embedding_dim=EMBEDDING_DIM,
            feature_type=FeatureType.CATEGORICAL,
            feature_hint=FeatureHint.ITEM_ID,
        ),
        TensorFeatureInfo(
            name="rating",
            is_seq=True,
            feature_type=FeatureType.NUMERICAL,
            tensor_dim=1,
            embedding_dim=EMBEDDING_DIM,  # must match item_id's, SumAggregator requires it
            feature_sources=[TensorFeatureSource(FeatureSource.INTERACTIONS, "rating")],
        ),
    ]
)

In [14]:
from replay.nn.transform.template import make_default_sasrec_transforms
from replay.nn.transform import RenameTransform, CopyTransform, GroupTransform

item_id_name = tensor_schema.item_id_feature_name

custom_predict_transforms = [
    RenameTransform({f"{item_id_name}_mask": "padding_mask"}),
    CopyTransform({item_id_name: "seen_ids"}),          # <- survives the grouping below
    GroupTransform({"feature_tensors": tensor_schema.names}),
]

transforms = make_default_sasrec_transforms(tensor_schema)
# TODO: Delete if not needed
transforms["predict"] = custom_predict_transforms   # only override the predict split

In [11]:
MAX_SEQ_LEN = 50

train_metadata = {
    "train": {
        "item_id": {"shape": MAX_SEQ_LEN + 1, "padding": tensor_schema["item_id"].padding_value},
        "rating": {"shape": MAX_SEQ_LEN + 1, "padding": 0.0},
    },
    "validate": {
        "item_id": {"shape": MAX_SEQ_LEN, "padding": tensor_schema["item_id"].padding_value},
        "rating": {"shape": MAX_SEQ_LEN, "padding": 0.0},
        "ground_truth": {"shape": 1, "padding": -1}
    },
}

In [17]:
from replay.data.nn import ParquetModule

BATCH_SIZE = 32

parquet_module = ParquetModule(
    train_path=TRAIN_PATH,
    validate_path=VAL_PATH,
    batch_size=BATCH_SIZE,
    metadata=train_metadata,
    transforms=transforms,
)

/tmp/ipykernel_5106/1761019238.py:5: UserWarning: The following dataset paths aren't provided: test,predict. Make sure to disable these stages in your Lightning Trainer configuration.
  parquet_module = ParquetModule(

In [18]:
from replay.nn.sequential import SasRec

NUM_BLOCKS = 2
NUM_HEADS = 2
DROPOUT = 0.3

sasrec = SasRec.from_params(
    schema=tensor_schema,
    embedding_dim=EMBEDDING_DIM,
    max_sequence_length=MAX_SEQ_LEN,
    num_heads=NUM_HEADS,
    num_blocks=NUM_BLOCKS,
    dropout=DROPOUT,
)

In [19]:
from replay.nn.lightning import LightningModule

model = LightningModule(sasrec)

In [20]:
import torch
import lightning as L

torch.set_num_threads(1)
torch.set_num_interop_threads(1)

# L.seed_everything(42);

In [21]:
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.loggers import CSVLogger

from replay.nn.lightning.callback import ComputeMetricsCallback


checkpoint_callback = ModelCheckpoint(
    dirpath="sasrec/checkpoints",
    save_top_k=1,
    verbose=True,
    monitor="recall@10",
    mode="max",
)

validation_metrics_callback = ComputeMetricsCallback(
    metrics=["map", "ndcg", "recall"],
    ks=[1, 5, 10, 20],
    item_count=NUM_UNIQUE_ITEMS,
    # verbose=False,
)

csv_logger = CSVLogger(save_dir="sasrec/logs/train", name="SasRec-example")

trainer = L.Trainer(
    max_epochs=5,
    callbacks=[checkpoint_callback, validation_metrics_callback],
    logger=csv_logger,
)

trainer.fit(model, datamodule=parquet_module)

INFO: GPU available: True (cuda), used: True

GPU available: True (cuda), used: True

INFO: TPU available: False, using: 0 TPU cores

TPU available: False, using: 0 TPU cores

INFO: You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

INFO:
  | Name  | Type   | Params | Mode
-----------------------------------------
0 | model | SasRec | 1.1 M  | train
-----------------------------------------
1.1 M     Trainable params
0         Non-trainable params
1.1 M     Total params
4.236     Total estimated model params size (MB)
42        Modules in train mode
0         Modules in eval mode

  | Name  | Type   | Params | Mode
-----------------------------------------
0 | model | SasRec | 1.1 M  | train
-----------------------------------------
1.1 M     Trainable params
0         Non-trainable params
1.1 M     Total params
4.236     Total estimated model params size (MB)
42        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/utilities/data.py:123: Your `IterableDataset` has `__len__` defined. In combination with multi-process data loading (when num_workers > 1), `__len__` could be inaccurate if each worker is not configured independently to avoid having duplicate data.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 0, global step 6280: 'recall@10' reached 0.11002 (best 0.11002), saving model to '/content/sasrec/checkpoints/epoch=0-step=6280.ckpt' as top 1

k             1         5         10        20
map     0.011894  0.028138  0.034509  0.039512
ndcg    0.011894  0.036305  0.051909  0.070360
recall  0.011894  0.061404  0.110024  0.183456

Epoch 0, global step 6280: 'recall@10' reached 0.11002 (best 0.11002), saving model to '/content/sasrec/checkpoints/epoch=0-step=6280.ckpt' as top 1

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 1, global step 12560: 'recall@10' reached 0.12674 (best 0.12674), saving model to '/content/sasrec/checkpoints/epoch=1-step=12560.ckpt' as top 1

k             1         5         10        20
map     0.013163  0.032630  0.039779  0.045252
ndcg    0.013163  0.042355  0.059857  0.079989
recall  0.013163  0.072223  0.126745  0.206771

Epoch 1, global step 12560: 'recall@10' reached 0.12674 (best 0.12674), saving model to '/content/sasrec/checkpoints/epoch=1-step=12560.ckpt' as top 1

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 2, global step 18840: 'recall@10' reached 0.13272 (best 0.13272), saving model to '/content/sasrec/checkpoints/epoch=2-step=18840.ckpt' as top 1

k             1         5         10        20
map     0.013556  0.034038  0.041496  0.047081
ndcg    0.013556  0.044315  0.062564  0.083165
recall  0.013556  0.075896  0.132717  0.214723

Epoch 2, global step 18840: 'recall@10' reached 0.13272 (best 0.13272), saving model to '/content/sasrec/checkpoints/epoch=2-step=18840.ckpt' as top 1

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 3, global step 25120: 'recall@10' reached 0.13418 (best 0.13418), saving model to '/content/sasrec/checkpoints/epoch=3-step=25120.ckpt' as top 1

k             1         5         10        20
map     0.013023  0.033771  0.041384  0.046895
ndcg    0.013023  0.044139  0.062806  0.083140
recall  0.013023  0.075970  0.134180  0.215136

Epoch 3, global step 25120: 'recall@10' reached 0.13418 (best 0.13418), saving model to '/content/sasrec/checkpoints/epoch=3-step=25120.ckpt' as top 1

Validation: |          | 0/? [00:00<?, ?it/s]

INFO: Epoch 4, global step 31400: 'recall@10' reached 0.13636 (best 0.13636), saving model to '/content/sasrec/checkpoints/epoch=4-step=31400.ckpt' as top 1

k             1         5         10        20
map     0.013476  0.034563  0.042304  0.047961
ndcg    0.013476  0.045015  0.064012  0.084827
recall  0.013476  0.077085  0.136359  0.219108

Epoch 4, global step 31400: 'recall@10' reached 0.13636 (best 0.13636), saving model to '/content/sasrec/checkpoints/epoch=4-step=31400.ckpt' as top 1

INFO: `Trainer.fit` stopped: `max_epochs=5` reached.

`Trainer.fit` stopped: `max_epochs=5` reached.

In [22]:
best_model_path = checkpoint_callback.best_model_path
best_epoch = int(best_model_path.split("epoch=")[1].split("-")[0])

best_model_path

'/content/sasrec/checkpoints/epoch=4-step=31400.ckpt'

### Inference

In [23]:
sasrec = SasRec.from_params(
    schema=tensor_schema,
    embedding_dim=EMBEDDING_DIM,
    max_sequence_length=MAX_SEQ_LEN,
    num_heads=NUM_HEADS,
    num_blocks=NUM_BLOCKS,
    dropout=DROPOUT,
    excluded_features=None,
)

best_model = LightningModule.load_from_checkpoint(best_model_path, model=sasrec)
best_model.eval();

In [24]:
inference_metadata = {
    "predict": {
        "user_id": {},
        "item_id": {"shape": MAX_SEQ_LEN, "padding": tensor_schema["item_id"].padding_value},
        "rating": {"shape": MAX_SEQ_LEN, "padding": 0.0},
    }
}

parquet_module = ParquetModule(
    predict_path=PREDICT_PATH,
    batch_size=BATCH_SIZE,
    metadata=inference_metadata,
    transforms=transforms,
)

/tmp/ipykernel_5106/1018093252.py:9: UserWarning: The following dataset paths aren't provided: train,validate,test. Make sure to disable these stages in your Lightning Trainer configuration.
  parquet_module = ParquetModule(

In [25]:
from replay.nn.lightning.callback import PandasTopItemsCallback
from replay.nn.lightning.postprocessor import SeenItemsFilter

csv_logger = CSVLogger(save_dir="sasrec/logs/test", name="SasRec-example")
seen_filter = SeenItemsFilter(item_count=NUM_UNIQUE_ITEMS, seen_items_column="seen_ids")

TOPK = [1, 5, 10, 20]

pandas_prediction_callback = PandasTopItemsCallback(
    top_k=max(TOPK),
    query_column="user_id",
    item_column="item_id",
    rating_column="score",
    postprocessors=[seen_filter],
)

trainer = L.Trainer(callbacks=[pandas_prediction_callback], logger=csv_logger, inference_mode=True)
trainer.predict(best_model, datamodule=parquet_module, return_predictions=False)

pandas_res = pandas_prediction_callback.get_result()

INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

INFO: GPU available: True (cuda), used: True

GPU available: True (cuda), used: True

INFO: TPU available: False, using: 0 TPU cores

TPU available: False, using: 0 TPU cores

INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/usr/local/lib/python3.12/dist-packages/lightning/pytorch/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
/usr/local/lib/python3.12/dist-packages/lightning/pytorch/utilities/data.py:123: Your `IterableDataset` has `__len__` defined. In combination with multi-process data loading (when num_workers > 1), `__len__` could be inaccurate if each worker is not configured independently to avoid having duplicate data.

Predicting: |          | 0/? [00:00<?, ?it/s]

In [26]:
pandas_res

        user_id item_id     score
0             0    6188  3.528302
0             0    7703  3.308642
0             0    3969  3.055112
0             0     574  3.035537
0             0    4515  2.804952
...         ...     ...       ...
200946   200946    3177  5.129805
200946   200946   10432  5.094892
200946   200946    2321  5.064738
200946   200946   10623  5.019598
200946   200946    1719  5.016489

[4018940 rows x 3 columns]

In [27]:
pandas_res.to_csv("temp/sasrec_results.csv", index=False)

In [28]:
from replay.metrics import MAP, OfflineMetrics, Precision, Recall, NDCG
from replay.metrics.torch_metrics_builder import metrics_to_df

In [29]:
result_metrics = OfflineMetrics(
    [Recall(TOPK), Precision(TOPK), MAP(TOPK), NDCG(TOPK)],
    item_column="item_id",
    query_column="user_id",
    rating_column="score",
)(pandas_res, test_gt.explode("item_id"))

In [30]:
metrics_to_df(result_metrics)

k                1         5         10        20
MAP        0.034626  0.059056  0.066697  0.072029
NDCG       0.034626  0.070668  0.089337  0.108920
Precision  0.034626  0.021229  0.016422  0.012100
Recall     0.034626  0.106147  0.164217  0.241994

In [31]:
# encoder = LabelEncoder.load(ENCODER_PATH)
pandas_res = encoder.inverse_transform(pandas_res)  # actually keep the decoded result now
pandas_res

        user_id  item_id     score
0             1    18203  3.528302
0             1    26561  3.308642
0             1    11386  3.055112
0             1      784  3.035537
0             1    12498  2.804952
...         ...      ...       ...
200946   200948    10193  5.129805
200946   200948    49026  5.094892
200946   200948     8681  5.064738
200946   200948    51876  5.019598
200946   200948     4638  5.016489

[4018940 rows x 3 columns]

In [32]:
pandas_res.to_csv("temp/sasrec_results_inversed.csv", index=False)

In [34]:
# !mkdir -p drive/MyDrive/COMP720Project/cf
!rm -r drive/MyDrive/COMP720Project/cf
!cp -r sasrec drive/MyDrive/COMP720Project/cf/sasrec
!cp -r temp drive/MyDrive/COMP720Project/cf/temp

In [ ]:
# pandas_res.to_csv()

In [5]:
try:
  pandas_res.info()
except Exception:
  # Read saved file
  pandas_res = pd.read_csv("drive/MyDrive/COMP720Project/cf/temp/sasrec_results_inversed.csv")

In [7]:
try:
  test_events.info()
except Exception:
  # Read saved file
  test_events = pd.read_parquet("drive/MyDrive/COMP720Project/cf/temp/data/test.parquet")

In [10]:
try:
  best_model.eval()
except Exception:
  from replay.nn.sequential import SasRec
  from replay.nn.lightning import LightningModule
  # import lightning as L
  # import torch
  # Read saved file # Edit best model path if needed
  MAX_SEQ_LEN = 50
  EMBEDDING_DIM = 64
  NUM_BLOCKS = 2
  NUM_HEADS = 2
  DROPOUT = 0.3
  best_model_path = "drive/MyDrive/COMP720Project/cf/sasrec/checkpoints/epoch=4-step=31400.ckpt"
  sasrec = SasRec.from_params(
    schema=tensor_schema,
    embedding_dim=EMBEDDING_DIM,
    max_sequence_length=MAX_SEQ_LEN,
    num_heads=NUM_HEADS,
    num_blocks=NUM_BLOCKS,
    dropout=DROPOUT,
    excluded_features=None,
    )

  best_model = LightningModule.load_from_checkpoint(best_model_path, model=sasrec)
  best_model.eval()

In [17]:
import torch.nn.functional as F

item_embeddings = best_model.model.body.embedder.get_item_weights()

def explain_by_similarity_and_rating(user_history_item_ids, user_ratings, recommended_item_id, top_n=3):
    rec_vec = item_embeddings[recommended_item_id]
    hist_vecs = item_embeddings[user_history_item_ids]
    sims = F.cosine_similarity(rec_vec.unsqueeze(0), hist_vecs)
    top_idx = sims.topk(min(top_n, len(user_history_item_ids))).indices
    return [
        {
            "item_id": user_history_item_ids[i],
            "similarity": sims[i].item(),
            "your_rating": user_ratings[i],
        }
        for i in top_idx
    ]

In [12]:
def format_explanation_collab(explanation, rec_name):
    def bucket(sim):
        if sim > 0.8: return "very similar to"
        if sim > 0.6: return "similar to"
        if sim > 0.4: return "related to"
        return None

    lines = []
    for exp in explanation:
        if bucket(exp["similarity"]) is None:
            continue
        title = movie_names.get(item_id_decoder[exp["item_id"]], "an unknown title")
        lines.append(f'{title} (your rating: {exp["your_rating"]})')

    if not lines:
        return f'"{rec_name}" is broadly similar to your recent viewing.'
    return f'Because you enjoyed {", ".join(lines)}, we think you\'ll like "{rec_name}".'

In [19]:
item_id_decoder = encoder.inverse_mapping["item_id"]

movie_names = {
    item_id_decoder.get(int(row.item_id), int(row.item_id)): row.title
    for row in item_features_encoded.itertuples()
}

In [ ]:
user_histories = (
    test_events.set_index("user_id")[["item_id", "rating"]]
    .to_dict(orient="index")
)
# user_histories

In [14]:
from tqdm import tqdm

def add_explanations_collab(pandas_res, user_histories):
    explanations = []
    for _, row in tqdm(pandas_res.iterrows()):
        user_id = row["user_id"]
        rec_item_id_raw = int(row["item_id"])          # already raw, post inverse_transform
        history = user_histories.get(user_id)
        if history is None:
            explanations.append(None)
            continue

        recommended_item_id_encoded = encoder.mapping["item_id"].get(rec_item_id_raw)
        if recommended_item_id_encoded is None:
            explanations.append(None)
            continue

        explanation = explain_by_similarity_and_rating(
            history["item_id"], history["rating"], recommended_item_id_encoded
        )
        rec_name = movie_names.get(rec_item_id_raw, "Unknown title")
        explanations.append(format_explanation_collab(explanation, rec_name))

    pandas_res = pandas_res.copy()
    pandas_res["explanation"] = explanations
    return pandas_res

In [15]:
MAX_SAMPLE = 1000

In [20]:
pandas_res_with_explanations = add_explanations_collab(pandas_res[:MAX_SAMPLE], user_histories)
pandas_res_with_explanations[["user_id", "item_id", "score", "explanation"]].head(10)

1000it [00:00, 4957.11it/s]

,user_id,item_id,score,explanation
0,1,18203,3.528302,Because you enjoyed Prêt-à-Porter (your rating...
1,1,26561,3.308642,Because you enjoyed Circle of Friends (your ra...
2,1,11386,3.055112,"Because you enjoyed Nell (your rating: 5.0), F..."
3,1,784,3.035537,Because you enjoyed Prêt-à-Porter (your rating...
4,1,12498,2.804952,Because you enjoyed Boys on the Side (your rat...
5,1,145,2.757824,Because you enjoyed Prêt-à-Porter (your rating...
6,1,16619,2.710667,Because you enjoyed When a Man Loves a Woman (...
7,1,68924,2.696463,Because you enjoyed Circle of Friends (your ra...
8,1,703,2.661210,Because you enjoyed Four Weddings and a Funera...
9,1,11239,2.625349,Because you enjoyed Prêt-à-Porter (your rating...

In [21]:
pandas_res_with_explanations.to_csv("drive/MyDrive/COMP720Project/cf/temp/explanations.csv")