## Install Dependency

In [4]:
try:
  from google.colab import drive
  drive.mount('/content/drive')
  path = "/content/drive/MyDrive/COMP720Project/"
except Exception:
  path = "../data/"

Mounted at /content/drive

In [5]:
import pip
pip.main([
    'install',
    'pandas',
    'sentence-transformers',
    'scipy',
    'scikit-learn',
    'nltk',
    'tqdm',
    'spacy',
    ])

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)

Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)

Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)

Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)

Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)

Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)

Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)

Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)

Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)

Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)

Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)

Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)

Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)

Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)

Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)

Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)

Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)

Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)

Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)

Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)

Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)

Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)

Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)

Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.26.8)

Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)

Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.13.4)

Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)

Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)

Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)

Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)

Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)

Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)

Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)

Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)

Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)

Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)

Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)

Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)

Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)

Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)

Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.6.17)

Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)

Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)

Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)

Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)

Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)

Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)

Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)

Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)

Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)

Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)

Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)

Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)

Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)

Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)

Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)

Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)

Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)

Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)

Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)

Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)

Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)

Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)

Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)

Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)

Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)

Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)

Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)

Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.0)

Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)

Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.6)

Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)

Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)

Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)

Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)

Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)

Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)

Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)

Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

0

In [7]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from sentence_transformers import SentenceTransformer
import re
from tqdm import tqdm
import spacy
import os
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import MinMaxScaler
from pathlib import Path


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

TensorFlow version 2.20.0 available.

JAX version 0.7.2 available.

In [8]:
!pip install replay-rec[torch] -q
!pip install pyspark==3.3.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.9/827.9 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 50.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 370.7/370.7 kB 20.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 38.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
Collecting pyspark==3.3.2
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 5.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5 (from pyspark==3.3.2)
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 20.9 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824009 sha256=0c7d7f8e7bcad3f7b044afad62a0babb08e8baefaf6bdec4c99a2980253b0a68
  Stored in directory: /root/.cache/pip/wheels/93/99/74/4ba9a39bf51affed2cbf91a45688ea2a125775239338534f85
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.9
    Uninstalling py4j-0.10.9.9:
      Successfully uninstalled py4j-0.10.9.9
  Attempting uninstall: pyspark
    Found existing installation: pyspark 4.0.3
    Uninstalling pyspark-4.0.3:
      Successfully uninstalled pyspark-4.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 1.1.0 requires pyspark[connect]~=4.0.0, but you have pyspark 3.3.2 which is incompatible.
Successfully installed py4j-0.10.9.5 pyspark-3.3.2

In [9]:
from replay.preprocessing import LabelEncoder, LabelEncodingRule, SequenceEncodingRule

### Read and Clean Interaction

In [10]:
interactions_df = pd.read_csv(os.path.join(path, "filtered_movie_ratings_merged.csv"))
interactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31418661 entries, 0 to 31418660
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
 4   tmdbId     int64
dtypes: float64(1), int64(4)
memory usage: 1.2 GB

In [11]:
interactions_df.dropna(inplace=True)
interactions_df.reset_index(inplace=True, drop=True)

interactions_df = interactions_df.rename(columns={'userId': 'user_id', 'tmdbId': 'item_id'})
interactions_df.drop(columns=['movieId'], inplace=True)

interactions_df["user_id"] = interactions_df["user_id"].astype("int64")
interactions_df["item_id"] = interactions_df["item_id"].astype("int64")
interactions_df["timestamp"] = interactions_df["timestamp"].astype("int64")
interactions_df["rating"] = interactions_df["rating"].astype("float32")

# per-user ordinal ordering -- needed by groupby_sequences(sort_col="timestamp")
# in every downstream notebook, so we bake it in once, here.
interactions_df = interactions_df.sort_values(by="timestamp")
interactions_df["timestamp"] = interactions_df.groupby("user_id").cumcount()

interactions_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31418661 entries, 3919931 to 8509586
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   user_id    int64
 1   rating     float32
 2   timestamp  int64
 3   item_id    int64
dtypes: float32(1), int64(3)
memory usage: 1.1 GB

### Read and Prepare item content features

In [12]:
movie_df = pd.read_csv(os.path.join(path, "tmdb_movie_data_parsed_progressed_lemmaed.csv"))
movie_df.rename(columns={"id": "item_id"}, inplace=True)
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15711 entries, 0 to 15710
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   budget           15711 non-null  int64
 1   genres           15711 non-null  object
 2   item_id          15711 non-null  int64
 3   revenue          15711 non-null  int64
 4   runtime          15711 non-null  int64
 5   title            15711 non-null  object
 6   year             15711 non-null  int64
 7   weighted_rating  15711 non-null  float64
 8   description      15711 non-null  object
 9   keywords         15062 non-null  object
 10  crew             15711 non-null  object
 11  cast             15711 non-null  object
 12  productions      15711 non-null  object
dtypes: float64(1), int64(5), object(7)
memory usage: 1.6+ MB

In [13]:
movie_df["genres"] = movie_df["genres"].apply(
    lambda x: literal_eval(x) if isinstance(x, str) else x
)
movie_df

,budget,genres,item_id,revenue,runtime,title,year,weighted_rating,description,keywords,crew,cast,productions
0,30000000,"[Family, Comedy, Animation, Adventure]",862,401157969,81,Toy Story,1995,7.974369,"lead by Woody , Andy 's toy live happily in hi...",rescue friendship mission jealousy villain bul...,"['writer_alec_sokolow', 'producer_edwin_catmul...","['actor_tom_hanks', 'actor_tim_allen', 'actor_...",['production_pixar']
1,65000000,"[Adventure, Fantasy, Family]",8844,262821940,104,Jumanji,1995,7.243814,when sibling Judy and Peter discover an enchan...,base on novel or book giant insect board game ...,"['writer_jim_strain', 'director_joe_johnston',...","['actor_robin_williams', 'actor_kirsten_dunst'...","['production_tristar_pictures', 'production_in..."
2,25000000,"[Romance, Comedy]",15602,71518503,101,Grumpier Old Men,1995,6.482411,a family wedding reignite the ancient feud bet...,fishing sequel old man good friend wedding ita...,"['director_howard_deutch', 'writer_mark_steven...","['actor_walter_matthau', 'actor_jack_lemmon', ...","['production_lancaster_gate', 'production_warn..."
3,16000000,"[Comedy, Drama, Romance]",31357,81452156,127,Waiting to Exhale,1995,6.297186,"cheat on , mistreat and step on , the woman be...",base on novel or book single mother divorce an...,"['director_forest_whitaker', 'writer_terry_mcm...","['actor_whitney_houston', 'actor_angela_basset...",['production_20th_century_fox']
4,0,"[Comedy, Family]",11862,76594107,106,Father of the Bride Part II,1995,6.287352,just when George Banks have recover from his d...,daughter baby parent child relationship midlif...,"['producer_nancy_meyers', 'writer_nancy_meyers...","['actor_steve_martin', 'actor_diane_keaton', '...","['production_touchstone_pictures', 'production..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15706,10000000,"[Comedy, Drama]",9034,38068353,98,The Banger Sisters,2002,5.745638,"in the late ' 60 , the self - proclaim belle o...",friendship tattoo rock star groupie past prom ...,"['director_bob_dolman', 'writer_bob_dolman', '...","['actor_goldie_hawn', 'actor_susan_sarandon', ...","['production_fox_searchlight_pictures', 'produ..."
15707,35000000,"[Action, Adventure, Drama, Romance, War]",9093,29882645,132,The Four Feathers,2002,6.635344,a young british officer resign his post when h...,army escape bravery loyalty british empire isl...,"['writer_michael_schiffer', 'writer_hossein_am...","['actor_heath_ledger', 'actor_wes_bentley', 'a...","['production_paramount_pictures', 'production_..."
15708,30000000,"[Thriller, Crime]",9039,13414416,106,Trapped,2002,6.195109,when their daughter be abduct by experienced k...,ransom kidnap hostage psychopath telephone maniac,"['director_luis_mandoki', 'writer_greg_iles', ...","['actor_charlize_theron', 'actor_courtney_love...","['production_senator_film', 'production_propag..."
15709,8000000,"[Comedy, Thriller, Mystery]",1958,42400000,111,8 Women,2002,6.883085,eight woman gather to celebrate Christmas in a...,daughter upper class father murder musical fam...,"['writer_françois_ozon', 'director_françois_oz...","['actor_catherine_deneuve', 'actor_isabelle_hu...","['production_fidélité_productions', 'productio..."
15710,0,"[Drama, Romance]",23550,500930,106,His Secret Life,2001,7.239475,when Antonia 's husband Massimo be kill in a c...,aid affectation male homosexuality family angr...,"['writer_gianni_romoli', 'writer_ferzan_özpete...","['actor_margherita_buy', 'actor_stefano_accors...","['production_les_films_balenciaga', 'productio..."

In [14]:
embeddding = SentenceTransformer("BAAI/bge-m3", trust_remote_code=True)
sentences = (movie_df["description"]).tolist()  # TODO: Experiment with different combination

No device provided, using cuda:0

HTTP Request: GET https://huggingface.co/api/agent-harnesses "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

WARNING: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/modules.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/modules.json "HTTP/1.1 200 OK"

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config_sentence_transformers.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config_sentence_transformers.json "HTTP/1.1 200 OK"

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

Loading SentenceTransformer model from BAAI/bge-m3.

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config_sentence_transformers.json "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/README.md "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/README.md "HTTP/1.1 200 OK"

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/modules.json "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/sentence_bert_config.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/sentence_bert_config.json "HTTP/1.1 200 OK"

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config.json "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3 "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3/commits/main "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3/discussions?p=0 "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3/commits/refs%2Fpr%2F130 "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/refs%2Fpr%2F130/model.safetensors.index.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/refs%2Fpr%2F130/model.safetensors "HTTP/1.1 302 Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/tokenizer_config.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config.json "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/config.json "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/tokenizer_config.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/sentencepiece.bpe.model "HTTP/1.1 302 Found"

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/tokenizer.json "HTTP/1.1 302 Found"

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/special_tokens_map.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/special_tokens_map.json "HTTP/1.1 200 OK"

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3 "HTTP/1.1 200 OK"

HTTP Request: HEAD https://huggingface.co/BAAI/bge-m3/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"

HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"

HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-m3/5617a9f61b028005a4858fdac845db406aefb181/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-m3 "HTTP/1.1 200 OK"

In [15]:
tokenizer = embeddding.tokenizer
token_count = []
for text in sentences:
    tokens = tokenizer.encode(text, truncation=False)
    token_count.append(len(tokens))
movie_df['tokenCount'] = token_count
# Optimizing the model for a speed boost
print("Default max_seq_length:", embeddding.max_seq_length)
embeddding.max_seq_length = max(token_count)
print("Updated max_seq_length:", embeddding.max_seq_length)

Default max_seq_length: 8192
Updated max_seq_length: 293

In [16]:
embeddings = embeddding.encode(sentences)
movie_df['embeddings'] = list(embeddings)
movie_df.info()

Batches:   0%|          | 0/491 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15711 entries, 0 to 15710
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   budget           15711 non-null  int64
 1   genres           15711 non-null  object
 2   item_id          15711 non-null  int64
 3   revenue          15711 non-null  int64
 4   runtime          15711 non-null  int64
 5   title            15711 non-null  object
 6   year             15711 non-null  int64
 7   weighted_rating  15711 non-null  float64
 8   description      15711 non-null  object
 9   keywords         15062 non-null  object
 10  crew             15711 non-null  object
 11  cast             15711 non-null  object
 12  productions      15711 non-null  object
 13  tokenCount       15711 non-null  int64
 14  embeddings       15711 non-null  object
dtypes: float64(1), int64(6), object(8)
memory usage: 1.8+ MB

In [17]:
movie_df["keywords"].fillna("", inplace=True)

/tmp/ipykernel_2476/20696900.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_df["keywords"].fillna("", inplace=True)

In [18]:
tfidf = TfidfVectorizer(max_features=5000, min_df=2)   # min_df=2 drops keywords that appear in only 1 movie -- pure noise for similarity
tfidf_matrix = tfidf.fit_transform(movie_df["keywords"])

In [19]:
svd = TruncatedSVD(n_components=128, random_state=42)
keyword_vecs = svd.fit_transform(tfidf_matrix)

# sklearn defaults to float64 -- keep everything float32 downstream
keyword_vecs = keyword_vecs.astype(np.float32)
movie_df["keyword_embedding"] = keyword_vecs.tolist()

print(svd.explained_variance_ratio_.sum())   # e.g. 0.6 means SVD retained 60% of the variance

0.2798301116531925

In [20]:
# Identify integer columns to normalize (excluding 'item_id')
numeric_cols = ['budget', 'revenue', 'runtime', 'year']

scaler = MinMaxScaler()
movie_df[numeric_cols] = scaler.fit_transform(movie_df[numeric_cols]).astype(np.float32)

print("Normalized integer columns in movie_df:")
print(movie_df[numeric_cols].head())

Normalized integer columns in movie_df:
     budget   revenue   runtime      year
0  0.042857  0.137209  0.138462  0.769231
1  0.092857  0.089893  0.177778  0.769231
2  0.035714  0.024462  0.172650  0.769231
3  0.022857  0.027859  0.217094  0.769231
4  0.000000  0.026198  0.181197  0.769231

### Fit an Encoder

In [21]:
encoder = LabelEncoder(
    [
        LabelEncodingRule("user_id"),
        LabelEncodingRule("item_id"),
    ]
)
encoder.rules[0].fit(interactions_df)
encoder.rules[1].fit(movie_df)

encoded_interactions = encoder.transform(interactions_df)
encoded_interactions

          rating  timestamp  user_id  item_id
0            4.0          0    25061      934
1            5.0          0    30916      594
2            3.0          1    30916      453
3            3.0          2    30916     2160
4            5.0          0    43719     2160
...          ...        ...      ...      ...
31418656     3.0       1641    54314    12757
31418657     3.5       1642    54314    14717
31418658     2.5       1643    54314    14927
31418659     2.5       1644    54314    11649
31418660     2.5       1645    54314    13181

[31418661 rows x 4 columns]

In [22]:
item_features_encoded = encoder.rules[1].transform(movie_df)

item_features_encoded["genre_names"] = item_features_encoded["genres"]

genre_encoder = LabelEncoder(
    [
        SequenceEncodingRule("genres"),
    ]
)
genre_encoder.rules[0].fit(item_features_encoded)
item_features_encoded = genre_encoder.transform(item_features_encoded)

item_features_encoded["item_numerics"] = list(
    item_features_encoded[numeric_cols].values.astype(np.float32)
)
item_features_encoded

,budget,revenue,runtime,title,year,weighted_rating,description,keywords,crew,cast,productions,tokenCount,embeddings,keyword_embedding,item_id,genre_names,genres,item_numerics
0,0.042857,0.137209,0.138462,Toy Story,0.769231,7.974369,"lead by Woody , Andy 's toy live happily in hi...",rescue friendship mission jealousy villain bul...,"['writer_alec_sokolow', 'producer_edwin_catmul...","['actor_tom_hanks', 'actor_tim_allen', 'actor_...",['production_pixar'],91,"[0.004056659, 0.0031747434, -0.033042207, -0.0...","[0.09566071629524231, 0.026224475353956223, -0...",645,"[Family, Comedy, Animation, Adventure]","[8, 4, 3, 2]","[0.042857144, 0.13720873, 0.13846155, 0.7692308]"
1,0.092857,0.089893,0.177778,Jumanji,0.769231,7.243814,when sibling Judy and Peter discover an enchan...,base on novel or book giant insect board game ...,"['writer_jim_strain', 'director_joe_johnston',...","['actor_robin_williams', 'actor_kirsten_dunst'...","['production_tristar_pictures', 'production_in...",108,"[-0.0062281056, 0.039710753, -0.048255924, 0.0...","[0.3215295374393463, -0.19007861614227295, 0.1...",2361,"[Adventure, Fantasy, Family]","[2, 9, 8]","[0.092857145, 0.08989342, 0.17777778, 0.7692308]"
2,0.035714,0.024462,0.172650,Grumpier Old Men,0.769231,6.482411,a family wedding reignite the ancient feud bet...,fishing sequel old man good friend wedding ita...,"['director_howard_deutch', 'writer_mark_steven...","['actor_walter_matthau', 'actor_jack_lemmon', ...","['production_lancaster_gate', 'production_warn...",100,"[-0.0156483, 0.020313662, -0.062312685, 0.0159...","[0.08081933856010437, 0.05002164840698242, -0....",5607,"[Romance, Comedy]","[14, 4]","[0.035714287, 0.024461592, 0.17264958, 0.7692308]"
3,0.022857,0.027859,0.217094,Waiting to Exhale,0.769231,6.297186,"cheat on , mistreat and step on , the woman be...",base on novel or book single mother divorce an...,"['director_forest_whitaker', 'writer_terry_mcm...","['actor_whitney_houston', 'actor_angela_basset...",['production_20th_century_fox'],96,"[-0.02099574, 0.019866997, -0.039964158, -0.02...","[0.2527885138988495, -0.004739802330732346, 0....",8395,"[Comedy, Drama, Romance]","[4, 7, 14]","[0.022857143, 0.027859215, 0.21709402, 0.7692308]"
4,0.000000,0.026198,0.181197,Father of the Bride Part II,0.769231,6.287352,just when George Banks have recover from his d...,daughter baby parent child relationship midlif...,"['producer_nancy_meyers', 'writer_nancy_meyers...","['actor_steve_martin', 'actor_diane_keaton', '...","['production_touchstone_pictures', 'production...",98,"[0.0057701496, 0.022376291, -0.04018611, 0.033...","[0.13189169764518738, 0.13584260642528534, -0....",4273,"[Comedy, Family]","[4, 8]","[0.0, 0.026197609, 0.18119659, 0.7692308]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15706,0.014286,0.013021,0.167521,The Banger Sisters,0.823077,5.745638,"in the late ' 60 , the self - proclaim belle o...",friendship tattoo rock star groupie past prom ...,"['director_bob_dolman', 'writer_bob_dolman', '...","['actor_goldie_hawn', 'actor_susan_sarandon', ...","['production_fox_searchlight_pictures', 'produ...",134,"[0.021240057, 0.03611524, -0.052031722, 0.0658...","[0.07197848707437515, 0.04253310337662697, -0....",2462,"[Comedy, Drama]","[4, 7]","[0.014285714, 0.013020582, 0.16752137, 0.8230769]"
15707,0.050000,0.010221,0.225641,The Four Feathers,0.823077,6.635344,a young british officer resign his post when h...,army escape bravery loyalty british empire isl...,"['writer_michael_schiffer', 'writer_hossein_am...","['actor_heath_ledger', 'actor_wes_bentley', 'a...","['production_paramount_pictures', 'production_...",112,"[-0.010103188, 0.013699847, -0.042551182, -0.0...","[0.057048872113227844, 5.07199001731351e-05, -...",2506,"[Action, Adventure, Drama, Romance, War]","[1, 2, 7, 14, 18]","[0.05, 0.010220811, 0.22564103, 0.8230769]"
15708,0.042857,0.004588,0.181197,Trapped,0.823077,6.195109,when their daughter be abduct by experienced k...,ransom kidnap hostage psychopath telephone maniac,"['director_luis_mandoki', 'writer_greg_iles', ...","['actor_charlize_theron', 'actor_courtney_love...","['production_senator_film', 'production_propag...",46,"[-0.0007059251, 0.023286743, -0.057791125, -0....","[0.021266555413603783, 0.00540075171738863, -0...",2467,"[Thriller, Crime]","[17, 5]","[0.042857144, 0.004588155, 0.18119659, 0.8230769]"
15709,0.011429,0.014502,0.189744,8 Women,0.823077,6.883085,eight woman gather to celebrate Christmas in a...,daughter upper class father murder musical fam...,"['writer_françois_ozon', 'director_françois_oz...","['actor_catherine_deneuve', 'actor_isabelle_hu...","['production_fidélité_productions', 'productio...",67,"[0.012633885, 0.016316697, -0.042706802, 0.011...","[0.1423259824514389, 0.062037982046604156, -0....",1131,"[Comedy, Thriller, Mystery]","[4, 17, 13]","[0.011428571, 0.014502142, 0.1897436, 0.8230769]"
15710,0.000000,0.000171,0.181197,His Secret Life,0.815385,7.239475,when Antonia 's husband Massimo be kill in a c...,aid affectation male homosexuality family angr...,"['writer_gianni_romoli', 'writer_ferzan_özpete...","['actor_margherita_buy', 'actor_stefano_accors...","['production_les_films_balenciaga', 'productio...",42,"[-0.0144947395, 0.0062674684, -0.033462334, 0....","[0.059589482843875885, 0.02553064189851284, -0...",7171,"[Drama, Romance]","[7, 14]","[0.0, 0.00017133392, 0.18119659, 0.8153846]"

### Persist everything to Drive

In [23]:
# Define paths
ENCODED_DIR = Path(path) / "encoded"
ENCODED_DIR.mkdir(parents=True, exist_ok=True)

ENCODER_PATH = ENCODED_DIR / "encoder"
INTERACTIONS_PATH = ENCODED_DIR / "encoded_interactions.parquet"
ITEM_FEATURES_PATH = ENCODED_DIR / "item_features_encoded.parquet"

In [24]:
encoded_interactions.to_parquet(INTERACTIONS_PATH)

item_features_encoded[
    ["item_id", "title", "genres", "genre_names", "item_numerics", "embeddings", "keyword_embedding"]
].to_parquet(ITEM_FEATURES_PATH)

encoder.save(ENCODER_PATH)

print("Saved:")
print(" -", ENCODER_PATH)
print(" -", INTERACTIONS_PATH)
print(" -", ITEM_FEATURES_PATH)

/usr/local/lib/python3.12/dist-packages/replay/preprocessing/label_encoder.py:1001: UserWarning: There is already LabelEncoder object saved at the given path. File will be overwrited.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/replay/preprocessing/label_encoder.py:563: UserWarning: There is already LabelEncodingRule object saved at the given path. File will be overwrited.
  warnings.warn(msg)

Saved:
 - /content/drive/MyDrive/COMP720Project/encoded/encoder
 - /content/drive/MyDrive/COMP720Project/encoded/encoded_interactions.parquet
 - /content/drive/MyDrive/COMP720Project/encoded/item_features_encoded.parquet