In [4]:
try:
  from google.colab import drive
  drive.mount('/content/drive')
  IN_COLAB = True
  work_dir = '/content/drive/MyDrive/COMP720Project/SampledExplanation'
except:
  IN_COLAB = False
  work_dir = input()

Mounted at /content/drive

In [5]:
# !mkdir /content/drive/MyDrive/COMP720Project/SampledExplanation
# !cp /content/drive/MyDrive/COMP720Project/hbf/explanation_res.csv /content/drive/MyDrive/COMP720Project/SampledExplanation/explanations_hbf.csv
# !cp /content/drive/MyDrive/COMP720Project/cf/temp/explanations.csv /content/drive/MyDrive/COMP720Project/SampledExplanation/explanations_cf.csv
# !cp /content/drive/MyDrive/COMP720Project/rcbf_all_features/temp/explanations.csv /content/drive/MyDrive/COMP720Project/SampledExplanation/explanations_cbf.csv

In [6]:
import os
os.chdir(work_dir)
os.listdir(work_dir)

['explanations_cf.csv',
 'explanations_cbf.csv',
 'explanations_hbf.csv',
 'summary_means.csv',
 'scored_cbf.csv',
 'score_distributions.csv',
 'scored_cf.csv',
 'scored_hbf.csv']

In [ ]:
import re
import numpy as np
import pandas as pd

SAMPLE_PERS = 100
RANDOM_SEED = 42

In [21]:
pd.set_option('max_colwidth', 512)
pd.set_option('display.max_rows', 500)

In [8]:
FILES = {
    "cbf": ("explanations_cbf.csv", "Content-Based"),
    "cf": ("explanations_cf.csv", "Collaborative"),
    "hbf": ("explanations_hbf.csv", "Hybrid"),
}

In [9]:
################
### Patterns ###
################

PAT_WATCH = re.compile(
    r'Because you watched "(?P<src>.*?)", which (?P<clauses>.*?), '
    r'we think you\'ll like "(?P<rec>.*?)"\.'
)
PAT_NO_HISTORY = re.compile(
    r'"(?P<rec>.*?)" is recommended based on your overall viewing patterns\.'
)
PAT_CF_ITEMS = re.compile(
    r'Because you enjoyed (?P<items>.*?), we think you\'ll like "(?P<rec>.*?)"\.'
)
PAT_CF_GENERIC = re.compile(
    r'"(?P<rec>.*?)" is broadly similar to your recent viewing\.'
)
ITEM_PAT = re.compile(r'(?P<title>.*?) \(your rating: (?P<rating>[\d.]+)\)')

# PAT_WATCH captures the whole "which ... ," middle clause as one blob, since
# the generator (explanations.py) joins its reason clauses with " and " in
# whatever order/subset fired (genre isn't always first, and isn't guaranteed
# to be present at all) rather than a fixed sequence of optional groups.
# Splitting that blob on " and " and matching each piece below is what lets
# parse_cbf_hbf handle any combination.
CLAUSE_GENRE = re.compile(r'shares the (?P<genres>[^()]*) genre\(s\)')
CLAUSE_THEME = "has a similar theme/plot"
CLAUSE_STORY = "touches on similar story elements"
CLAUSE_TASTE = "is often watched by users with similar taste to yours"
CLAUSE_STYLE = "is broadly similar in style"

In [10]:
def parse_cbf_hbf(exp):
    m = PAT_WATCH.match(exp)
    if m:
        src, rec = m.group("src").strip(), m.group("rec").strip()
        clauses = [c.strip() for c in m.group("clauses").split(" and ")]

        genres = []
        theme = story = taste = False
        recognized = 0
        for clause in clauses:
            gm = CLAUSE_GENRE.fullmatch(clause)
            if gm:
                genres = [g.strip() for g in gm.group("genres").split(",") if g.strip()]
                recognized += 1
            elif clause == CLAUSE_THEME:
                theme = True
                recognized += 1
            elif clause == CLAUSE_STORY:
                story = True
                recognized += 1
            elif clause == CLAUSE_TASTE:
                taste = True
                recognized += 1
            # else: unrecognized clause text (e.g. the CLAUSE_STYLE fallback,
            # which only ever appears alone) -- falls through to style_generic below.

        if genres:
            template = "genre"
        elif recognized == 0:
            # No genre and nothing else recognized either -- covers CLAUSE_STYLE
            # ("is broadly similar in style") and any unrecognized clause text.
            template = "style_generic"
        else:
            template = "+".join(name for name, present in
                                 (("theme", theme), ("story", story), ("taste", taste)) if present)

        return {"template": template, "src": src, "rec": rec,
                "n_genres": len(genres), "theme": theme, "story": story, "taste": taste}

    m = PAT_NO_HISTORY.match(exp)
    if m:
        return {"template": "no_history", "src": None, "rec": m.group("rec").strip(),
                "n_genres": 0, "theme": False, "story": False, "taste": False}

    return {"template": "unparsed", "src": None, "rec": None,
            "n_genres": 0, "theme": False, "story": False, "taste": False}

In [11]:
def parse_cf(exp):
    m = PAT_CF_ITEMS.match(exp)
    if m:
        items_str = m.group("items")
        parts = re.split(r"(?<=\)), ", items_str)
        titles, ratings = [], []
        for p in parts:
            im = ITEM_PAT.match(p.strip())
            if im:
                titles.append(im.group("title").strip())
                ratings.append(float(im.group("rating")))
        return {"template": "items", "rec": m.group("rec").strip(), "titles": titles,
                "ratings": ratings, "n_items": len(titles)}
    m = PAT_CF_GENERIC.match(exp)
    if m:
        return {"template": "generic", "rec": m.group("rec").strip(), "titles": [], "ratings": [], "n_items": 0}
    return {"template": "unparsed", "rec": None, "titles": [], "ratings": [], "n_items": 0}

In [12]:

results = {}

for key, (fname, label) in FILES.items():
    df = pd.read_csv(fname)

    rows = []
    for _, row in df.iterrows():
        exp = row["explanation"]
        if key == "cf":
            feat = parse_cf(exp)
            n_evidence = feat["n_items"]
            self_rec = feat["rec"] is not None and feat["rec"].strip().lower() in [t.lower() for t in feat["titles"]]
        else:
            feat = parse_cbf_hbf(exp)
            n_evidence = feat["n_genres"]
            self_rec = (feat["src"] is not None and feat["rec"] is not None
                        and feat["src"].strip().lower() == feat["rec"].strip().lower())

        rows.append({
            "user_id": row["user_id"], "item_id": row["item_id"], "explanation": exp,
            "template": feat["template"], "n_evidence": n_evidence, "self_rec_bug": self_rec,
        })
    parsed = pd.DataFrame(rows)
    parsed.to_csv(f"scored_{key}.csv", index=False)
    results[key] = (label, parsed)

# ---- Parsing report ----
print("=" * 70)
print("Parsed the full explanation file per method (no sampling)")
print("=" * 70)

======================================================================
Parsed the full explanation file per method (no sampling)
======================================================================

In [13]:
summary_rows = []
for key, (label, parsed) in results.items():
    self_rec_rate = parsed["self_rec_bug"].mean()
    template_dist = parsed["template"].value_counts(normalize=True).round(3).to_dict()
    unparsed_count = int((parsed["template"] == "unparsed").sum())
    print(f"\n--- {label} ---")
    print(f"  Unparsed count: {unparsed_count} / {len(parsed)}")
    print(f"  Self-recommendation bug rate: {self_rec_rate:.1%}")
    print(f"  Template mix: {template_dist}")
    summary_rows.append({
        "method": label, "file": key,
        "unparsed_count": unparsed_count,
        "self_rec_bug_rate": round(self_rec_rate, 3),
    })

summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv("summary_means.csv", index=False)
print("\n" + "=" * 70)
print("SUMMARY TABLE")
print("=" * 70)
display(summary_df)

--- Content-Based ---
  Unparsed count: 0 / 1000
  Self-recommendation bug rate: 0.0%
  Template mix: {'genre': 0.974, 'style_generic': 0.019, 'story': 0.007}

--- Collaborative ---
  Unparsed count: 0 / 1000
  Self-recommendation bug rate: 0.0%
  Template mix: {'items': 0.553, 'generic': 0.447}

--- Hybrid ---
  Unparsed count: 0 / 1000
  Self-recommendation bug rate: 0.0%
  Template mix: {'genre': 0.945, 'taste': 0.042, 'style_generic': 0.007, 'story': 0.003, 'story+taste': 0.002, 'theme+taste': 0.001}

======================================================================
SUMMARY TABLE
======================================================================

          method file  unparsed_count  self_rec_bug_rate
0  Content-Based  cbf               0                0.0
1  Collaborative   cf               0                0.0
2         Hybrid  hbf               0                0.0

## LLM plausibility judge (sample 50 items)

In [15]:
!pip install anthropic

Collecting anthropic
  Downloading anthropic-1.4.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from anthropic) (4.14.2)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.13/dist-packages (from anthropic) (0.18.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from anthropic) (2.12.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from anthropic) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from anthropic) (2.13.4)
Requirement already satisfied: sniffio<2,>=1 in /usr/local/lib/python3.13/dist-packages (from anthropic) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.13/dist-packages (from anthropic) (4.16.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=3.5.0->anthropic) (3.19)
Requirement already satisfied: httpcore2==2.12.0 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->anthropic) (2.12.0)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->anthropic) (0.10.4)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore2==2.12.0->httpx2<3,>=2.0.0->anthropic) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->anthropic) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->anthropic) (0.4.4)
Downloading anthropic-1.4.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.0 MB/s eta 0:00:0000:010:01
Installing collected packages: anthropic
Successfully installed anthropic-1.4.0

In [ ]:
import os
import time

import anthropic

if not os.environ.get("ANTHROPIC_API_KEY"):
    import getpass
    os.environ["ANTHROPIC_API_KEY"] = getpass.getpass("Anthropic API key: ")

client = anthropic.Anthropic()

JUDGE_MODEL = "claude-sonnet-5"

JUDGE_PROMPT = """You will be shown one movie recommendation explanation at a time. Each states a reason for recommending a film based on something the user previously watched or rated.
Using your knowledge of the films named, judge whether the stated reason is credible: would a viewer who knows these films find this a sensible basis for the recommendation, or would the connection seem arbitrary?
Rate plausibility from 1 to 5, where 1 means the cited films have no meaningful relationship to the recommendation and 5 means the connection is clear and well-founded. Judge only what the sentence actually argues -- do not credit a recommendation that happens to be good if the stated reason does not support it.
Give the rating and one sentence of justification naming the specific films. Do not consider how much evidence is cited; a reason citing one film may be more credible than one citing three.
You have a web_search tool. Use it to confirm plot, genre, or thematic details of the named films whenever you are not fully confident from memory alone -- the judgment should reflect what the films are actually about, not a guess.
Respond with nothing but the rating and justification, in exactly this format:
Rating: <integer 1-5>
Justification: <one sentence, naming the specific films>"""

LLM_SAMPLE_N = 50   # rows per file
LLM_RNG_SEED = 42

In [17]:
RATING_PAT = re.compile(r"Rating:\s*([1-5]).*?Justification:\s*(.+)", re.DOTALL)

def judge_plausibility(explanation):
    try:
        response = client.messages.create(
            model=JUDGE_MODEL,
            max_tokens=8192,
            system=JUDGE_PROMPT,
            output_config={"effort": "medium"},
            tools=[{"type": "web_search_20260209", "name": "web_search", "max_uses": 3}],
            messages=[{"role": "user", "content": explanation}],
        )
    except anthropic.APIError as e:
        return {"rating": None, "justification": f"API error: {e}"}

    text = " ".join(b.text for b in response.content if b.type == "text").strip()
    m = RATING_PAT.search(text)
    if m:
        return {"rating": int(m.group(1)), "justification": m.group(2).strip()}
    return {"rating": None, "justification": text or None}

In [ ]:
llm_rows = []

for key, (label, parsed) in results.items():
    sample = parsed.sample(n=min(LLM_SAMPLE_N, len(parsed)), random_state=LLM_RNG_SEED)
    for i, (_, row) in enumerate(sample.iterrows()):
        judged = judge_plausibility(row["explanation"])
        llm_rows.append({
            "method": label, "file": key,
            "user_id": row["user_id"], "item_id": row["item_id"],
            "explanation": row["explanation"], "template": row["template"],
            "llm_plausibility": judged["rating"], "llm_justification": judged["justification"],
        })
        print(f"[{label}] {i + 1}/{len(sample)}  rating={judged['rating']}")

llm_df = pd.DataFrame(llm_rows)
llm_df.to_csv("llm_plausibility_sample.csv", index=False)

[Content-Based] 1/50  rating=3
[Content-Based] 2/50  rating=3
[Content-Based] 3/50  rating=3
[Content-Based] 4/50  rating=5
[Content-Based] 5/50  rating=5
[Content-Based] 6/50  rating=4
[Content-Based] 7/50  rating=4
[Content-Based] 8/50  rating=5
[Content-Based] 9/50  rating=2
[Content-Based] 10/50  rating=4
[Content-Based] 11/50  rating=4
[Content-Based] 12/50  rating=3
[Content-Based] 13/50  rating=2
[Content-Based] 14/50  rating=4
[Content-Based] 15/50  rating=3
[Content-Based] 16/50  rating=4
[Content-Based] 17/50  rating=2
[Content-Based] 18/50  rating=5
[Content-Based] 19/50  rating=2
[Content-Based] 20/50  rating=4
[Content-Based] 21/50  rating=3
[Content-Based] 22/50  rating=3
[Content-Based] 23/50  rating=4
[Content-Based] 24/50  rating=3
[Content-Based] 25/50  rating=1
[Content-Based] 26/50  rating=2
[Content-Based] 27/50  rating=4
[Content-Based] 28/50  rating=4
[Content-Based] 29/50  rating=3
[Content-Based] 30/50  rating=2
[Content-Based] 31/50  rating=5
[Content-Based] 32/50  rating=2
[Content-Based] 33/50  rating=5
[Content-Based] 34/50  rating=3
[Content-Based] 35/50  rating=3
[Content-Based] 36/50  rating=3
[Content-Based] 37/50  rating=3
[Content-Based] 38/50  rating=5
[Content-Based] 39/50  rating=3
[Content-Based] 40/50  rating=4
[Content-Based] 41/50  rating=2
[Content-Based] 42/50  rating=2
[Content-Based] 43/50  rating=4
[Content-Based] 44/50  rating=4
[Content-Based] 45/50  rating=2
[Content-Based] 46/50  rating=2
[Content-Based] 47/50  rating=5
[Content-Based] 48/50  rating=2
[Content-Based] 49/50  rating=4
[Content-Based] 50/50  rating=2
[Collaborative] 1/50  rating=4
[Collaborative] 2/50  rating=1
[Collaborative] 3/50  rating=3
[Collaborative] 4/50  rating=5
[Collaborative] 5/50  rating=1
[Collaborative] 6/50  rating=2
[Collaborative] 7/50  rating=1
[Collaborative] 8/50  rating=1
[Collaborative] 9/50  rating=1
[Collaborative] 10/50  rating=1
[Collaborative] 11/50  rating=3
[Collaborative] 12/50  rating=1
[Collaborative] 13/50  rating=1
[Collaborative] 14/50  rating=1
[Collaborative] 15/50  rating=1
[Collaborative] 16/50  rating=3
[Collaborative] 17/50  rating=1
[Collaborative] 18/50  rating=2
[Collaborative] 19/50  rating=2
[Collaborative] 20/50  rating=2
[Collaborative] 21/50  rating=3
[Collaborative] 22/50  rating=2
[Collaborative] 23/50  rating=1
[Collaborative] 24/50  rating=2
[Collaborative] 25/50  rating=3
[Collaborative] 26/50  rating=3
[Collaborative] 27/50  rating=3
[Collaborative] 28/50  rating=1
[Collaborative] 29/50  rating=1
[Collaborative] 30/50  rating=1
[Collaborative] 31/50  rating=3
[Collaborative] 32/50  rating=1
[Collaborative] 33/50  rating=1
[Collaborative] 34/50  rating=1
[Collaborative] 35/50  rating=1
[Collaborative] 36/50  rating=1
[Collaborative] 37/50  rating=2
[Collaborative] 38/50  rating=1
[Collaborative] 39/50  rating=1
[Collaborative] 40/50  rating=1
[Collaborative] 41/50  rating=2
[Collaborative] 42/50  rating=1
[Collaborative] 43/50  rating=1
[Collaborative] 44/50  rating=2
[Collaborative] 45/50  rating=1
[Collaborative] 46/50  rating=1
[Collaborative] 47/50  rating=2
[Collaborative] 48/50  rating=1
[Collaborative] 49/50  rating=1
[Collaborative] 50/50  rating=2
[Hybrid] 1/50  rating=2
[Hybrid] 2/50  rating=5
[Hybrid] 3/50  rating=2
[Hybrid] 4/50  rating=5
[Hybrid] 5/50  rating=4
[Hybrid] 6/50  rating=2
[Hybrid] 7/50  rating=1
[Hybrid] 8/50  rating=5
[Hybrid] 9/50  rating=3
[Hybrid] 10/50  rating=2
[Hybrid] 11/50  rating=1
[Hybrid] 12/50  rating=2
[Hybrid] 13/50  rating=2
[Hybrid] 14/50  rating=3
[Hybrid] 15/50  rating=4
[Hybrid] 16/50  rating=2
[Hybrid] 17/50  rating=1
[Hybrid] 18/50  rating=5
[Hybrid] 19/50  rating=4
[Hybrid] 20/50  rating=4
[Hybrid] 21/50  rating=4
[Hybrid] 22/50  rating=4
[Hybrid] 23/50  rating=4
[Hybrid] 24/50  rating=1
[Hybrid] 25/50  rating=2
[Hybrid] 26/50  rating=2
[Hybrid] 27/50  rating=4
[Hybrid] 28/50  rating=2
[Hybrid] 29/50  rating=2
[Hybrid] 30/50  rating=3
[Hybrid] 31/50  rating=3
[Hybrid] 32/50  rating=3
[Hybrid] 33/50  rating=4
[Hybrid] 34/50  rating=5
[Hybrid] 35/50  rating=4
[Hybrid] 36/50  rating=4
[Hybrid] 37/50  rating=3
[Hybrid] 38/50  rating=3
[Hybrid] 39/50  rating=2
[Hybrid] 40/50  rating=3
[Hybrid] 41/50  rating=3
[Hybrid] 42/50  rating=3
[Hybrid] 43/50  rating=3
[Hybrid] 44/50  rating=2
[Hybrid] 45/50  rating=2
[Hybrid] 46/50  rating=2
[Hybrid] 47/50  rating=4
[Hybrid] 48/50  rating=3
[Hybrid] 49/50  rating=2
[Hybrid] 50/50  rating=4

,method,file,user_id,item_id,explanation,template,llm_plausibility,llm_justification
0,Content-Based,cbf,26,875,"Because you watched ""Harry Potter and the Deat...",genre,3,"Both ""Harry Potter and the Deathly Hallows: Pa..."
1,Content-Based,cbf,36,427,"Because you watched ""A Beautiful Mind"", which ...",genre,3,"Both ""A Beautiful Mind"" and ""To Kill a Mocking..."
2,Content-Based,cbf,37,7835,"Because you watched ""Iron Man"", which shares t...",genre,3,"""Iron Man"" and ""Inception"" both fall under Act..."
3,Content-Based,cbf,33,86,"Because you watched ""Howl's Moving Castle"", wh...",genre,5,"Both ""Howl's Moving Castle"" and ""Princess Mono..."
4,Content-Based,cbf,20,4122,"Because you watched ""A Nightmare on Elm Street...",genre,5,"""A Nightmare on Elm Street"" and ""Wes Craven's ..."
...,...,...,...,...,...,...,...,...
145,Hybrid,hbf,13,3691,"Because you watched ""The Ladies Man"", which sh...",genre,2,"""The Ladies Man"" is a comedy about a womanizin..."
146,Hybrid,hbf,46,401,"Because you watched ""Chinatown"", which shares ...",genre,4,"""Chinatown"" and ""Rear Window"" are both acclaim..."
147,Hybrid,hbf,30,14085,"Because you watched ""Lady Bird"", which shares ...",genre,3,"""Lady Bird"" and ""Isle of Dogs"" are both direct..."
148,Hybrid,hbf,21,15141,"Because you watched ""Close"", which shares the ...",genre,2,"""Close"" is a 2019 British action thriller film..."
149,Hybrid,hbf,41,2829,"Because you watched ""The Bridge on the River K...",genre,4,"""The Bridge on the River Kwai"" and ""Glory"" are..."

In [22]:
llm_df

,method,file,user_id,item_id,explanation,template,llm_plausibility,llm_justification
0,Content-Based,cbf,26,875,"Because you watched ""Harry Potter and the Deathly Hallows: Part 2"", which shares the Fantasy genre(s), we think you'll like ""Hellboy"".",genre,3,"Both ""Harry Potter and the Deathly Hallows: Part 2"" and ""Hellboy"" fall under the broad Fantasy genre with supernatural/magical elements and epic good-vs-evil battles, but their tone, setting (British boarding-school wizarding world vs. dark comic-book horror-action), and audience skew quite differently, making the shared-genre link plausible but fairly generic."
1,Content-Based,cbf,36,427,"Because you watched ""A Beautiful Mind"", which shares the Drama genre(s), we think you'll like ""To Kill a Mockingbird"".",genre,3,"Both ""A Beautiful Mind"" and ""To Kill a Mockingbird"" are acclaimed dramas built around a principled protagonist facing hostility (mental illness stigma vs. racial injustice), so the shared genre link is real but fairly generic and doesn't capture any deeper thematic connection beyond both being prestige dramas."
2,Content-Based,cbf,37,7835,"Because you watched ""Iron Man"", which shares the Action, Adventure, Science Fiction genre(s), we think you'll like ""Inception"".",genre,3,"""Iron Man"" and ""Inception"" both fall under Action/Adventure/Sci-Fi, but beyond broad genre overlap they differ sharply in tone, style, and narrative focus (superhero origin story vs. heist/dream-thriller), making the connection genre-technical rather than substantively meaningful."
3,Content-Based,cbf,33,86,"Because you watched ""Howl's Moving Castle"", which shares the Adventure, Animation, Fantasy genre(s) and touches on similar story elements, we think you'll like ""Princess Mononoke"".",genre,5,"Both ""Howl's Moving Castle"" and ""Princess Mononoke"" are Studio Ghibli fantasy adventures directed by Hayao Miyazaki that blend animation, magical transformation themes, and environmental/anti-war messaging, making the genre and thematic overlap well-founded."
4,Content-Based,cbf,20,4122,"Because you watched ""A Nightmare on Elm Street"", which shares the Horror genre(s) and touches on similar story elements, we think you'll like ""Wes Craven's New Nightmare"".",genre,5,"""A Nightmare on Elm Street"" and ""Wes Craven's New Nightmare"" are both directed by Wes Craven, feature Freddy Krueger and Nancy (Heather Langenkamp), and share horror/slasher themes, with the sequel directly building on the original's story and meta-mythology."
5,Content-Based,cbf,33,82,"Because you watched ""Howl's Moving Castle"", which shares the Adventure, Fantasy genre(s), we think you'll like ""The Lord of the Rings: The Return of the King"".",genre,4,"""Howl's Moving Castle"" and ""The Lord of the Rings: The Return of the King"" both belong squarely to the Adventure/Fantasy genre with epic quests, magic, and war themes, making genre-based similarity reasonable, though the films differ significantly in tone, animation style, and target audience."
6,Content-Based,cbf,31,511,"Because you watched ""Leaving Las Vegas"", which shares the Drama genre(s), we think you'll like ""Dead Man Walking"".",genre,4,"""Leaving Las Vegas"" and ""Dead Man Walking"" are both mid-90s serious dramas with heavyweight lead performances dealing with mortality and moral/emotional despair, so the genre link is real, though the connection is fairly generic since ""Drama"" alone covers a huge range of otherwise dissimilar films."
7,Content-Based,cbf,25,68,"Because you watched ""Reservoir Dogs"", which shares the Crime genre(s) and has a similar theme/plot, we think you'll like ""Snatch"".",genre,5,"""Reservoir Dogs"" and ""Snatch"" are both stylish, non-linear crime films featuring ensembles of criminals, heists gone wrong, dark humor, and violent underworld dealings, making the genre and thematic connection well-founded."
8,Content-Based,cbf,42,1217,"Because you watched ""Menace II Society"", which shares the Crime, Thriller genre(s) and touches on similar story elements, we think you'll like ""Nick of Time"".",genre,2,"""Menace II Society"" is a gritty urban crime drama about gang life and violence in South Central LA, while ""Nick of Time"" is a real-time political assassination thriller centered on a coerced accountant, so beyond both being loosely ""crime/thriller"" the actual story elements and settings share little in common."
9,Content-Based,cbf,6,3492,"Because you watched ""Sleepless in Seattle"", which shares the Comedy, Drama, Romance genre(s), we think you'll like ""It Could Happen to You"".",genre,4,"""Sleepless in Seattle"" and ""It Could Happen to You"" are both mid-1990s romantic comedy-dramas built around a chance-of-fate premise and gentle sentimental tone, so the shared Comedy/Drama/Romance genre link is a sensible, if fairly generic, basis for the recommendation."
10,Content-Based,cbf,40,1013,"Because you watched ""Star Trek"", which shares the Action, Adventure, Science Fiction genre(s), we think you'll like ""Iron Man"".",genre,4,"""Star Trek"" (2009) and ""Iron Man"" (2008) both belong squarely to the Action/Adventure/Science Fiction genre and share blockbuster tone, spectacle, and hero-origin storytelling, so the genre-based connection is reasonable even if not deeply thematic."
11,Content-Based,cbf,3,2794,"Because you watched ""Bowfinger"", which shares the Comedy genre(s), we think you'll like ""Romy and Michele's High School Reunion"".",genre,3,"""Bowfinger"" and ""Romy and Michele's High School Reunion"" are both 1990s comedies, but the former is a Hollywood filmmaking satire while the latter is a female-buddy reunion farce, so the shared ""Comedy"" tag is a valid but fairly generic and superficial basis for the recommendation."
12,Content-Based,cbf,31,2697,"Because you watched ""Babe"", which shares the Family, Fantasy genre(s), we think you'll like ""The Nightmare Before Christmas"".",genre,2,"""Babe"" is a live-action family film about a talking pig on a farm, while ""The Nightmare Before Christmas"" is a stop-motion dark musical fantasy centered on Halloween/Christmas mythology, so beyond a loose ""Family/Fantasy"" genre tag their tone, style, and content diverge significantly enough that the connection feels more arbitrary than meaningful."
13,Content-Based,cbf,48,1669,"Because you watched ""Forrest Gump"", which shares the Drama, Romance genre(s), we think you'll like ""Legends of the Fall"".",genre,4,"Both ""Forrest Gump"" and ""Legends of the Fall"" are sweeping historical dramas spanning decades with strong romance threads, so the shared Drama/Romance genre connection is credible even though their tones and settings differ."
14,Content-Based,cbf,46,740,"Because you watched ""Touch of Evil"", which shares the Drama, Thriller genre(s), we think you'll like ""The Manchurian Candidate"".",genre,3,"""Touch of Evil"" and ""The Manchurian Candidate"" are both dark, morally complex thrillers with political/corruption undertones and stylish direction, but beyond the shared broad genre labels of Drama/Thriller they have quite different plots (border town police corruption vs. Cold War brainwashing conspiracy), making the connection thematically loose rather than strongly grounded."
15,Content-Based,cbf,44,52,"Because you watched ""The Lord of the Rings: The Return of the King"", which shares the Action, Adventure genre(s), we think you'll like ""Indiana Jones and the Last Crusade"".",genre,4,"Both ""The Lord of the Rings: The Return of the King"" and ""Indiana Jones and the Last Crusade"" are epic action-adventure films involving perilous quests, mythic/legendary artifacts, and fantastical elements, so the shared genre link is reasonable though fairly generic."
16,Content-Based,cbf,14,2252,"Because you watched ""Good Will Hunting"", which shares the Drama genre(s), we think you'll like ""Cast Away"".",genre,2,"""Good Will Hunting"" is a character-driven drama about a genius mathematician's psychological growth through therapy and relationships, while ""Cast Away"" is a survival drama about isolation on a deserted island, so beyond both being loosely labeled ""Drama"" they share little thematic or narrative connection."
17,Content-Based,cbf,44,82,"Because you watched ""The Lord of the Rings: The Two Towers"", which shares the Action, Adventure, Fantasy genre(s) and has a similar theme/plot and touches on similar story elements, we think you'll like ""The Lord of the Rings: The Return of the King"".",genre,5,"""The Two Towers"" and ""The Return of the King"" are the second and third installments of the same trilogy, sharing the same characters, continuous plot, and Action/Adventure/Fantasy genre, making this an extremely well-founded recommendation."
18,Content-Based,cbf,38,3198,"Because you watched ""The First Wives Club"", which shares the Comedy genre(s), we think you'll like ""Swingers"".",genre,2,"""The First Wives Club"" is an ensemble comedy about middle-aged women avenging their husbands' betrayals, while ""Swingers"" is about young single men navigating the Los Angeles dating scene, so the shared ""Comedy"" genre label is too broad a connection to make this recommendation feel well-founded."
19,Content-Based,cbf,15,75,"Because you watched ""Valentine's Day"", which shares the Comedy, Romance genre(s) and touches on similar story elements, we think you'll like ""Pretty Woman"".",genre,4,"""Valentine's Day"" and ""Pretty Woman"" both belong squarely to the romantic comedy genre and center on love-story arcs with comedic elements, so the genre-based connection is reasonable even though ""Pretty Woman"" is a more specific two-lead story compared to ""Valentine's Day""'s ensemble format."
20,Content-Based,cbf,27,15164,"Because you watched ""Bullet Train"", which shares the Action, Thriller genre(s), we think you'll like ""Tenet"".",genre,3,"""Bullet Train"" and ""Tenet"" are both Action/Thriller films involving assassins and elaborate structural gimmicks, but genre overlap alone is a fairly shallow basis given how different their tones and storytelling approaches (dark comedy caper vs. time-inversion sci-fi puzzle) actually are."
21,Content-Based,cbf,8,754,"Because you watched ""Kiss Kiss Bang Bang"", which shares the Mystery genre(s) and has a similar theme/plot and touches on similar story elements, we think you'll like ""Mulholland Drive"".",genre,3,"Both ""Kiss Kiss Bang Bang"" and ""Mulholland Drive"" are neo-noir mysteries set in the Hollywood/LA world with twisty, self-aware plots, but the former is a wisecracking meta-comedy while the latter is a surreal psychological drama, so the genre link is real but the tonal/thematic match is loose."
22,Content-Based,cbf,18,373,"Because you watched ""Oliver & Company"", which shares the Animation, Comedy, Family genre(s), we think you'll like ""The Wrong Trousers"".",genre,4,"Both ""Oliver & Company"" and ""The Wrong Trousers"" are animated family comedies, so the shared-genre rationale is reasonable, though the connection is fairly generic since one is a Disney musical about street animals and the other a stop-motion Wallace and Gromit heist comedy."
23,Content-Based,cbf,26,1021,"Because you watched ""Planet of the Apes"", which shares the Action, Adventure, Science Fiction genre(s), we think you'll like ""Captain America: The First Avenger"".",genre,3,"""Planet of the Apes"" and ""Captain America: The First Avenger"" do share the broad Action/Adventure/Science Fiction genre umbrella, but beyond that shared classification their themes (post-apocalyptic social allegory vs. WWII superhero origin story) are quite different, making the connection genre-accurate but thematically shallow."
24,Content-Based,cbf,10,8380,"Because you watched ""Heat"", which shares the Drama genre(s), we think you'll like ""Richard III"".",genre,1,"""Heat"" is a crime thriller about rival cops and heist crews in modern Los Angeles, while ""Richard III"" is a Shakespearean historical tragedy about a scheming medieval English monarch, so a shared broad ""Drama"" genre label is far too generic to constitute a meaningful connection between these two films."
25,Content-Based,cbf,11,279,"Because you watched ""American Beauty"", which shares the Drama genre(s), we think you'll like ""Rain Man"".",genre,2,"""American Beauty"" and ""Rain Man"" are both dramas, but beyond that broad genre label they share little in theme, tone, or content—one is a satirical suburban midlife-crisis story and the other a road-trip film about an autistic savant and his brother—making the connection feel arbitrary."
26,Content-Based,cbf,5,436,"Because you watched ""Minority Report"", which shares the Action, Science Fiction, Thriller genre(s), we think you'll like ""The Matrix Reloaded"".",genre,4,"Both ""Minority Report"" and ""The Matrix Reloaded"" are big-budget Action/Sci-Fi/Thriller films with dystopian futuristic settings, chase sequences, and philosophical themes about free will versus determinism, making the genre-based connection reasonably sound even if the two franchises differ in tone."
27,Content-Based,cbf,49,138,"Because you watched ""Trainspotting"", which shares the Crime genre(s) and has a similar theme/plot, we think you'll like ""A Clockwork Orange"".",genre,4,"Both ""Trainspotting"" and ""A Clockwork Orange"" are crime-themed films exploring youth subcultures, addiction/deviance, and societal alienation with stylized, dark, satirical tones, making the thematic link reasonably credible even though their specific plots differ."
28,Content-Based,cbf,45,12297,"Because you watched ""Cloud Atlas"", which shares the Drama, Science Fiction genre(s) and touches on similar story elements, we think you'll like ""Her"".",genre,3,"""Cloud Atlas"" and ""Her"" both fall under speculative/science-fiction drama and explore themes of identity, connection, and consciousness across different times or forms of existence, but their tones, structures, and stories are quite different, making the connection more genre-level than deeply thematic."
29,Content-Based,cbf,47,5278,"Because you watched ""Nixon"", which shares the Drama, History genre(s), we think you'll like ""Rudy"".",genre,2,"""Nixon"" is a dark political epic about Richard Nixon's rise and downfall, while ""Rudy"" is an uplifting sports biopic about a underdog's quest to play college football, so beyond both being loosely ""Drama, History"" tagged, they share little thematic or tonal connection."
30,Content-Based,cbf,17,594,"Because you watched ""Psycho"", which shares the Mystery, Thriller genre(s), we think you'll like ""Se7en"".",genre,5,"""Psycho"" and ""Se7en"" are both landmark Mystery/Thriller films centered on disturbing psychological/serial-killer plots with shocking twist endings, making the genre-based connection well-founded."
31,Content-Based,cbf,6,1417,"Because you watched ""Sleepless in Seattle"", which shares the Comedy, Drama genre(s), we think you'll like ""The Adventures of Priscilla, Queen of the Desert"".",genre,2,"""Sleepless in Seattle"" is a mainstream heterosexual romantic comedy-drama while ""The Adventures of Priscilla, Queen of the Desert"" is a comedy-drama about drag queens on a road trip, so beyond the broad Comedy/Drama label the films share little thematic or stylistic connection."
32,Content-Based,cbf,31,3396,"Because you watched ""Sleepless in Seattle"", which shares the Comedy, Drama, Romance genre(s), we think you'll like ""Forget Paris"".",genre,5,"Both ""Sleepless in Seattle"" and ""Forget Paris"" are Billy Crystal/Nora Ephron-esque romantic comedy-dramas of the same early-90s era, sharing genre, tone, and even overlapping stars (Billy Crystal and Rita Wilson appear in both), making the genre-based connection sensible."
33,Content-Based,cbf,24,147,"Because you watched ""The Fugitive"", which shares the Action, Drama genre(s), we think you'll like ""Braveheart"".",genre,3,"""The Fugitive"" (a modern crime-thriller about a wrongly accused man on the run) and ""Braveheart"" (an epic historical war drama) both broadly fit Action/Drama, but their settings, tone, and specific themes differ enough that genre overlap alone is a fairly weak basis for the recommendation."
34,Content-Based,cbf,18,5475,"Because you watched ""Mulan"", which shares the Family genre(s), we think you'll like ""The Sound of Music"".",genre,3,"""Mulan"" and ""The Sound of Music"" are both family-oriented films with musical elements and themes of courage/duty, but beyond the shared ""Family"" genre label they differ significantly in setting, tone, and story (Chinese war epic with a heroine disguised as a soldier vs. an Austrian nun-turned-governess musical), making the connection generic rather than substantive."
35,Content-Based,cbf,9,13485,"Because you watched ""Captain America: The Winter Soldier"", which shares the Action, Adventure, Science Fiction genre(s) and touches on similar story elements, we think you'll like ""Spider-Man: Into the Spider-Verse"".",genre,3,"Both ""Captain America: The Winter Soldier"" and ""Spider-Man: Into the Spider-Verse"" are Action/Adventure/Science Fiction superhero films, but the former is a grounded political-conspiracy thriller while the latter is a multiverse-hopping animated origin story, so the genre overlap is real but the ""similar story elements"" claim is vague and not well-substantiated."
36,Content-Based,cbf,34,14079,"Because you watched ""The Duke of Burgundy"", which shares the Drama, Romance genre(s), we think you'll like ""The Shape of Water"".",genre,3,"""The Duke of Burgundy"" and ""The Shape of Water"" both blend romance with fantastical/unconventional relationship dynamics and lush visual style, but genre overlap alone (Drama/Romance) is a fairly generic basis given how different their settings, tone, and narrative approach actually are."
37,Content-Based,cbf,29,256,"Because you watched ""Jurassic Park"", which shares the Adventure, Science Fiction genre(s) and has a similar theme/plot and touches on similar story elements, we think you'll like ""The Lost World: Jurassic Park"".",genre,5,"""The Lost World: Jurassic Park"" is the direct sequel to ""Jurassic Park"", sharing the same dinosaur cloning premise, Adventure/Science Fiction genre classification, and core story elements, making this an especially well-founded recommendation."
38,Content-Based,cbf,45,12318,"Because you watched ""About Time"", which shares the Drama genre(s), we think you'll like ""Interstellar"".",genre,3,"""About Time"" and ""Interstellar"" both involve time as a central plot device and carry emotional family drama elements, but ""About Time"" is a romantic time-travel comedy-drama while ""Interstellar"" is a hard sci-fi space epic, so sharing only the broad ""Drama"" genre label is a fairly weak basis for the recommendation."
39,Content-Based,cbf,2,308,"Because you watched ""Chariots of Fire"", which shares the Drama, History genre(s), we think you'll like ""Schindler's List"".",genre,4,"""Chariots of Fire"" and ""Schindler's List"" are indeed both Drama/History films dealing with real historical events, though the former's uplifting sports/faith narrative differs sharply in tone and subject from the latter's Holocaust tragedy, making the genre link valid but thematically shallow."
40,Content-Based,cbf,16,1650,"Because you watched ""Monty Python and the Holy Grail"", which shares the Adventure, Comedy genre(s), we think you'll like ""Charlie's Angels"".",genre,2,"While both ""Monty Python and the Holy Grail"" and ""Charlie's Angels"" can be broadly tagged as comedy/adventure, they share almost nothing in tone, style, or substance—one is a surreal British satire and the other a glossy American action-comedy blockbuster, making the connection feel arbitrary and genre-label-driven rather than substantive."

In [23]:
print("=" * 70)
print(f"LLM plausibility sample: {LLM_SAMPLE_N} rows/file (seed={LLM_RNG_SEED})")
print("=" * 70)

for method, group in llm_df.groupby("method"):
    rated = group["llm_plausibility"].dropna()
    print(f"\n--- {method} ---")
    print(f"  Rated: {len(rated)} / {len(group)}")
    if len(rated):
        print(f"  Mean LLM plausibility: {rated.mean():.2f}")

display(llm_df[["method", "user_id", "item_id", "template", "llm_plausibility", "llm_justification"]])

======================================================================
LLM plausibility sample: 50 rows/file (seed=42)
======================================================================

--- Collaborative ---
  Rated: 50 / 50
  Mean LLM plausibility: 1.68

--- Content-Based ---
  Rated: 50 / 50
  Mean LLM plausibility: 3.30

--- Hybrid ---
  Rated: 50 / 50
  Mean LLM plausibility: 2.98

,method,user_id,item_id,template,llm_plausibility,llm_justification
0,Content-Based,26,875,genre,3,"Both ""Harry Potter and the Deathly Hallows: Part 2"" and ""Hellboy"" fall under the broad Fantasy genre with supernatural/magical elements and epic good-vs-evil battles, but their tone, setting (British boarding-school wizarding world vs. dark comic-book horror-action), and audience skew quite differently, making the shared-genre link plausible but fairly generic."
1,Content-Based,36,427,genre,3,"Both ""A Beautiful Mind"" and ""To Kill a Mockingbird"" are acclaimed dramas built around a principled protagonist facing hostility (mental illness stigma vs. racial injustice), so the shared genre link is real but fairly generic and doesn't capture any deeper thematic connection beyond both being prestige dramas."
2,Content-Based,37,7835,genre,3,"""Iron Man"" and ""Inception"" both fall under Action/Adventure/Sci-Fi, but beyond broad genre overlap they differ sharply in tone, style, and narrative focus (superhero origin story vs. heist/dream-thriller), making the connection genre-technical rather than substantively meaningful."
3,Content-Based,33,86,genre,5,"Both ""Howl's Moving Castle"" and ""Princess Mononoke"" are Studio Ghibli fantasy adventures directed by Hayao Miyazaki that blend animation, magical transformation themes, and environmental/anti-war messaging, making the genre and thematic overlap well-founded."
4,Content-Based,20,4122,genre,5,"""A Nightmare on Elm Street"" and ""Wes Craven's New Nightmare"" are both directed by Wes Craven, feature Freddy Krueger and Nancy (Heather Langenkamp), and share horror/slasher themes, with the sequel directly building on the original's story and meta-mythology."
5,Content-Based,33,82,genre,4,"""Howl's Moving Castle"" and ""The Lord of the Rings: The Return of the King"" both belong squarely to the Adventure/Fantasy genre with epic quests, magic, and war themes, making genre-based similarity reasonable, though the films differ significantly in tone, animation style, and target audience."
6,Content-Based,31,511,genre,4,"""Leaving Las Vegas"" and ""Dead Man Walking"" are both mid-90s serious dramas with heavyweight lead performances dealing with mortality and moral/emotional despair, so the genre link is real, though the connection is fairly generic since ""Drama"" alone covers a huge range of otherwise dissimilar films."
7,Content-Based,25,68,genre,5,"""Reservoir Dogs"" and ""Snatch"" are both stylish, non-linear crime films featuring ensembles of criminals, heists gone wrong, dark humor, and violent underworld dealings, making the genre and thematic connection well-founded."
8,Content-Based,42,1217,genre,2,"""Menace II Society"" is a gritty urban crime drama about gang life and violence in South Central LA, while ""Nick of Time"" is a real-time political assassination thriller centered on a coerced accountant, so beyond both being loosely ""crime/thriller"" the actual story elements and settings share little in common."
9,Content-Based,6,3492,genre,4,"""Sleepless in Seattle"" and ""It Could Happen to You"" are both mid-1990s romantic comedy-dramas built around a chance-of-fate premise and gentle sentimental tone, so the shared Comedy/Drama/Romance genre link is a sensible, if fairly generic, basis for the recommendation."
10,Content-Based,40,1013,genre,4,"""Star Trek"" (2009) and ""Iron Man"" (2008) both belong squarely to the Action/Adventure/Science Fiction genre and share blockbuster tone, spectacle, and hero-origin storytelling, so the genre-based connection is reasonable even if not deeply thematic."
11,Content-Based,3,2794,genre,3,"""Bowfinger"" and ""Romy and Michele's High School Reunion"" are both 1990s comedies, but the former is a Hollywood filmmaking satire while the latter is a female-buddy reunion farce, so the shared ""Comedy"" tag is a valid but fairly generic and superficial basis for the recommendation."
12,Content-Based,31,2697,genre,2,"""Babe"" is a live-action family film about a talking pig on a farm, while ""The Nightmare Before Christmas"" is a stop-motion dark musical fantasy centered on Halloween/Christmas mythology, so beyond a loose ""Family/Fantasy"" genre tag their tone, style, and content diverge significantly enough that the connection feels more arbitrary than meaningful."
13,Content-Based,48,1669,genre,4,"Both ""Forrest Gump"" and ""Legends of the Fall"" are sweeping historical dramas spanning decades with strong romance threads, so the shared Drama/Romance genre connection is credible even though their tones and settings differ."
14,Content-Based,46,740,genre,3,"""Touch of Evil"" and ""The Manchurian Candidate"" are both dark, morally complex thrillers with political/corruption undertones and stylish direction, but beyond the shared broad genre labels of Drama/Thriller they have quite different plots (border town police corruption vs. Cold War brainwashing conspiracy), making the connection thematically loose rather than strongly grounded."
15,Content-Based,44,52,genre,4,"Both ""The Lord of the Rings: The Return of the King"" and ""Indiana Jones and the Last Crusade"" are epic action-adventure films involving perilous quests, mythic/legendary artifacts, and fantastical elements, so the shared genre link is reasonable though fairly generic."
16,Content-Based,14,2252,genre,2,"""Good Will Hunting"" is a character-driven drama about a genius mathematician's psychological growth through therapy and relationships, while ""Cast Away"" is a survival drama about isolation on a deserted island, so beyond both being loosely labeled ""Drama"" they share little thematic or narrative connection."
17,Content-Based,44,82,genre,5,"""The Two Towers"" and ""The Return of the King"" are the second and third installments of the same trilogy, sharing the same characters, continuous plot, and Action/Adventure/Fantasy genre, making this an extremely well-founded recommendation."
18,Content-Based,38,3198,genre,2,"""The First Wives Club"" is an ensemble comedy about middle-aged women avenging their husbands' betrayals, while ""Swingers"" is about young single men navigating the Los Angeles dating scene, so the shared ""Comedy"" genre label is too broad a connection to make this recommendation feel well-founded."
19,Content-Based,15,75,genre,4,"""Valentine's Day"" and ""Pretty Woman"" both belong squarely to the romantic comedy genre and center on love-story arcs with comedic elements, so the genre-based connection is reasonable even though ""Pretty Woman"" is a more specific two-lead story compared to ""Valentine's Day""'s ensemble format."
20,Content-Based,27,15164,genre,3,"""Bullet Train"" and ""Tenet"" are both Action/Thriller films involving assassins and elaborate structural gimmicks, but genre overlap alone is a fairly shallow basis given how different their tones and storytelling approaches (dark comedy caper vs. time-inversion sci-fi puzzle) actually are."
21,Content-Based,8,754,genre,3,"Both ""Kiss Kiss Bang Bang"" and ""Mulholland Drive"" are neo-noir mysteries set in the Hollywood/LA world with twisty, self-aware plots, but the former is a wisecracking meta-comedy while the latter is a surreal psychological drama, so the genre link is real but the tonal/thematic match is loose."
22,Content-Based,18,373,genre,4,"Both ""Oliver & Company"" and ""The Wrong Trousers"" are animated family comedies, so the shared-genre rationale is reasonable, though the connection is fairly generic since one is a Disney musical about street animals and the other a stop-motion Wallace and Gromit heist comedy."
23,Content-Based,26,1021,genre,3,"""Planet of the Apes"" and ""Captain America: The First Avenger"" do share the broad Action/Adventure/Science Fiction genre umbrella, but beyond that shared classification their themes (post-apocalyptic social allegory vs. WWII superhero origin story) are quite different, making the connection genre-accurate but thematically shallow."
24,Content-Based,10,8380,genre,1,"""Heat"" is a crime thriller about rival cops and heist crews in modern Los Angeles, while ""Richard III"" is a Shakespearean historical tragedy about a scheming medieval English monarch, so a shared broad ""Drama"" genre label is far too generic to constitute a meaningful connection between these two films."
25,Content-Based,11,279,genre,2,"""American Beauty"" and ""Rain Man"" are both dramas, but beyond that broad genre label they share little in theme, tone, or content—one is a satirical suburban midlife-crisis story and the other a road-trip film about an autistic savant and his brother—making the connection feel arbitrary."
26,Content-Based,5,436,genre,4,"Both ""Minority Report"" and ""The Matrix Reloaded"" are big-budget Action/Sci-Fi/Thriller films with dystopian futuristic settings, chase sequences, and philosophical themes about free will versus determinism, making the genre-based connection reasonably sound even if the two franchises differ in tone."
27,Content-Based,49,138,genre,4,"Both ""Trainspotting"" and ""A Clockwork Orange"" are crime-themed films exploring youth subcultures, addiction/deviance, and societal alienation with stylized, dark, satirical tones, making the thematic link reasonably credible even though their specific plots differ."
28,Content-Based,45,12297,genre,3,"""Cloud Atlas"" and ""Her"" both fall under speculative/science-fiction drama and explore themes of identity, connection, and consciousness across different times or forms of existence, but their tones, structures, and stories are quite different, making the connection more genre-level than deeply thematic."
29,Content-Based,47,5278,genre,2,"""Nixon"" is a dark political epic about Richard Nixon's rise and downfall, while ""Rudy"" is an uplifting sports biopic about a underdog's quest to play college football, so beyond both being loosely ""Drama, History"" tagged, they share little thematic or tonal connection."
30,Content-Based,17,594,genre,5,"""Psycho"" and ""Se7en"" are both landmark Mystery/Thriller films centered on disturbing psychological/serial-killer plots with shocking twist endings, making the genre-based connection well-founded."
31,Content-Based,6,1417,genre,2,"""Sleepless in Seattle"" is a mainstream heterosexual romantic comedy-drama while ""The Adventures of Priscilla, Queen of the Desert"" is a comedy-drama about drag queens on a road trip, so beyond the broad Comedy/Drama label the films share little thematic or stylistic connection."
32,Content-Based,31,3396,genre,5,"Both ""Sleepless in Seattle"" and ""Forget Paris"" are Billy Crystal/Nora Ephron-esque romantic comedy-dramas of the same early-90s era, sharing genre, tone, and even overlapping stars (Billy Crystal and Rita Wilson appear in both), making the genre-based connection sensible."
33,Content-Based,24,147,genre,3,"""The Fugitive"" (a modern crime-thriller about a wrongly accused man on the run) and ""Braveheart"" (an epic historical war drama) both broadly fit Action/Drama, but their settings, tone, and specific themes differ enough that genre overlap alone is a fairly weak basis for the recommendation."
34,Content-Based,18,5475,genre,3,"""Mulan"" and ""The Sound of Music"" are both family-oriented films with musical elements and themes of courage/duty, but beyond the shared ""Family"" genre label they differ significantly in setting, tone, and story (Chinese war epic with a heroine disguised as a soldier vs. an Austrian nun-turned-governess musical), making the connection generic rather than substantive."
35,Content-Based,9,13485,genre,3,"Both ""Captain America: The Winter Soldier"" and ""Spider-Man: Into the Spider-Verse"" are Action/Adventure/Science Fiction superhero films, but the former is a grounded political-conspiracy thriller while the latter is a multiverse-hopping animated origin story, so the genre overlap is real but the ""similar story elements"" claim is vague and not well-substantiated."
36,Content-Based,34,14079,genre,3,"""The Duke of Burgundy"" and ""The Shape of Water"" both blend romance with fantastical/unconventional relationship dynamics and lush visual style, but genre overlap alone (Drama/Romance) is a fairly generic basis given how different their settings, tone, and narrative approach actually are."
37,Content-Based,29,256,genre,5,"""The Lost World: Jurassic Park"" is the direct sequel to ""Jurassic Park"", sharing the same dinosaur cloning premise, Adventure/Science Fiction genre classification, and core story elements, making this an especially well-founded recommendation."
38,Content-Based,45,12318,genre,3,"""About Time"" and ""Interstellar"" both involve time as a central plot device and carry emotional family drama elements, but ""About Time"" is a romantic time-travel comedy-drama while ""Interstellar"" is a hard sci-fi space epic, so sharing only the broad ""Drama"" genre label is a fairly weak basis for the recommendation."
39,Content-Based,2,308,genre,4,"""Chariots of Fire"" and ""Schindler's List"" are indeed both Drama/History films dealing with real historical events, though the former's uplifting sports/faith narrative differs sharply in tone and subject from the latter's Holocaust tragedy, making the genre link valid but thematically shallow."
40,Content-Based,16,1650,genre,2,"While both ""Monty Python and the Holy Grail"" and ""Charlie's Angels"" can be broadly tagged as comedy/adventure, they share almost nothing in tone, style, or substance—one is a surreal British satire and the other a glossy American action-comedy blockbuster, making the connection feel arbitrary and genre-label-driven rather than substantive."
41,Content-Based,4,458,genre,2,"""Beauty and the Beast"" (the Disney animated musical) and ""Interview with the Vampire"" both contain fantastical/supernatural elements, but the former is a romantic family musical while the latter is a dark, gothic horror drama about vampires, so the shared ""Fantasy"" label is too broad to make this a meaningful connection."
42,Content-Based,15,383,genre,4,"Both ""Valentine's Day"" and ""There's Something About Mary"" are ensemble/mainstream romantic comedies built around interlocking love stories with comic mishaps, so the shared Comedy-Romance genre link is a reasonable, if fairly generic, basis for the recommendation."
43,Content-Based,48,955,genre,4,"""The Net"" and ""Speed"" are both 1990s techno/action thrillers with Sandra Bullock in peril, so a genre-based match between the two Action/Thriller films is reasonably credible, though the connection is fairly generic rather than deeply thematic."
44,Content-Based,14,538,genre,2,"""A Beautiful Mind"" is a biographical drama about a mathematician's struggle with schizophrenia with a romantic subplot, while ""Top Gun"" is primarily an action film about fighter pilots with only a minor romance thread, so the shared ""Drama, Romance"" tags are technically present but the films' tone, subject matter, and genre emphasis are quite different, making the connection feel arbitrary."
45,Content-Based,13,2293,genre,2,"""Cops & Robbersons"" is a lighthearted crime comedy about a family whose house becomes a police stakeout, sharing only a superficial ""crime"" genre tag with ""John Q,"" a tense hostage drama, so the tonal and thematic gulf makes the ""Crime, Thriller"" link feel arbitrary."
46,Content-Based,46,770,genre,5,"Both ""The Maltese Falcon"" and ""The Third Man"" are classic film noir mysteries/thrillers with morally ambiguous protagonists, shadowy visual styles, and plots centered on deception and pursuit of a hidden truth, making the genre-based connection a sensible and well-founded basis for recommendation."
47,Content-Based,30,14682,genre,2,"""The Social Network"" is a dialogue-driven biographical drama about the founding of Facebook, while ""Joker"" is a character-study crime drama about mental illness and societal breakdown—both are broadly ""Drama"" but share little else in tone, subject, or style, making genre alone a weak basis for the recommendation."
48,Content-Based,21,6560,genre,4,"Both ""Stargate"" and ""Avatar"" are Action/Adventure/Science Fiction films centered on a human protagonist traveling to an alien/otherworldly civilization, encountering exotic cultures and ancient/spiritual mythology, and getting drawn into a conflict against a technologically superior oppressive force, so the genre and thematic overlap is genuine rather than arbitrary."
49,Content-Based,41,42,genre,2,"""Clear and Present Danger"" is a grounded political/military drama-thriller about drug cartels and government corruption, while ""Blade Runner"" is a neo-noir science fiction film about androids and dystopian futures, so while both can be loosely tagged ""Drama/Thriller,"" their tone, setting, and substance share little meaningful connection beyond a generic genre label."
50,Collaborative,27,1995,items,4,"The Mummy Returns and Lara Croft: Tomb Raider are close genre cousins as globe-trotting supernatural adventure films with archaeological treasure-hunting plots, though The Fast and the Furious's street-racing focus adds a somewhat weaker, more arbitrary connection to the mix."
51,Collaborative,37,15121,generic,1,"The recommendation gives no specific film or details about the user's ""recent viewing,"" so there is no way to assess whether any meaningful connection to ""The Sound of Music"" actually exists."
52,Collaborative,38,78,items,3,"Star Wars shares Blade Runner's science-fiction genre and visionary world-building, but Fargo (a dark crime dramedy) and Trainspotting (a gritty drug-culture drama) have little thematic or stylistic overlap with Blade Runner, making the connection only partially credible."
53,Collaborative,34,10515,items,5,"Howl's Moving Castle, Princess Mononoke, and Castle in the Sky are all Studio Ghibli films directed by Hayao Miyazaki with shared fantastical, adventure-driven storytelling styles, making the connection highly coherent even though Perfect Blue (a Satoshi Kon psychological thriller) is unrelated in genre and studio."
54,Collaborative,21,32146,items,1,"""Close"" is an intimate drama about adolescent friendship and grief, ""Outside the Wire"" and ""Stowaway"" are sci-fi action/drama films, none of which share genre, tone, or subject matter with ""Body Parts,"" a documentary exposing the industry practices behind filming sex scenes."
55,Collaborative,34,530,items,2,"Rosencrantz & Guildenstern Are Dead, And Now for Something Completely Different, and Monty Python's The Meaning of Life are absurdist/surreal live-action comedies, while ""A Grand Day Out"" is a gentle stop-motion Wallace & Gromit claymation short with a very different tone and humor style, making the connection tenuous beyond a loose ""British comedy"" link."
56,Collaborative,32,11971,items,1,"The Crow (a dark supernatural revenge/action film) and Casino (a gritty crime drama about the mob and Las Vegas) share no meaningful genre, tone, or thematic connection with Much Ado About Nothing (a Shakespearean romantic comedy), making the recommendation arbitrary."
57,Collaborative,26,98,items,1,"Memento (a nonlinear psychological thriller about memory loss) and Crouching Tiger, Hidden Dragon (a wuxia martial-arts romance) share little genre, tone, or thematic overlap with Gladiator (a Roman revenge epic), and the low rating given to Memento further undercuts the recommendation's basis."
58,Collaborative,43,8447,items,1,"Sarah's Key (Holocaust drama), Endless Love (teen romance), and Laggies (indie coming-of-age comedy) share no meaningful genre, tone, or thematic overlap with Angels and Insects (a Victorian-era period drama about entomology, class, and incest), making the connection arbitrary."
59,Collaborative,7,10436,generic,1,"The recommendation cites no specific prior film for comparison—only a vague reference to ""your recent viewing""—so there is no concrete basis to judge whether ""The Age of Innocence"" is genuinely similar to anything the viewer watched."